/* NURS 4510 Community Health Nursing — Exam 1 pack.
   Sources: "Community Exam 1 Learning Objectives" (Ch. 1, 2, 5, 7, 12, 15), "Epidemiology Q&A" (25 keyed
   questions) and the "NURS 4510 Study Guide" (25 keyed questions: family theory, family assessment,
   vulnerable populations). Keys follow the documents; questions written from the objectives use the
   objectives' own definitions and examples. */
(function () {
const C = 'nurs4510';
const OBJ = 'Community Exam 1 Learning Objectives', EPI = 'Epidemiology Q&A', SG = 'NURS 4510 Study Guide';
const Q = (source, topic, q, options, rationale, extra) => Object.assign({ course: C, source, topic, q, options, rationale, multi: false }, extra || {});
const o = (t, ok, why) => ({ t, ok, why });
const PREV = (level, q, why) => Q(OBJ, 'Levels of prevention', q, [o('Primary prevention', level === 'primary', 'Prevents the problem before it occurs.'), o('Secondary prevention', level === 'secondary', 'Finds it early: screening and early treatment.'), o('Tertiary prevention', level === 'tertiary', 'Manages an existing condition; rehabilitation, support, quality of life.')], why, { fw: 'prevention', step: level });

window.QUICKFIRE.push(
  /* ---------- Levels of prevention: "guaranteed to be on the exam" (scenario → level) ---------- */
  PREV('primary', 'A nurse gives influenza vaccinations at a community clinic. Which level of prevention is this?', 'Vaccination prevents the disease before it occurs. The objectives\' own example of primary prevention.'),
  PREV('secondary', 'A nurse runs a free blood-pressure screening at a grocery store. Which level of prevention is this?', 'Screening detects a problem early, before symptoms. The objectives\' own example of secondary prevention.'),
  PREV('tertiary', 'A nurse coordinates a stroke rehabilitation program. Which level of prevention is this?', 'Rehabilitation improves quality of life for an existing condition. The objectives\' own example of tertiary prevention.'),
  PREV('primary', 'During a home visit the nurse teaches a healthy family about a balanced diet. Which level of prevention is this?', 'Health promotion for a currently healthy family: primary (study guide Q2).'),
  PREV('tertiary', 'The nurse gives a family whose child has autism a list of autism support groups. Which level of prevention is this?', 'The condition already exists; support and coping are tertiary (study guide Q4).'),
  PREV('secondary', 'A school nurse performs scoliosis screening on sixth graders. Which level of prevention is this?', 'Screening finds a condition early.'),
  PREV('secondary', 'A nurse teaches women how to do monthly breast self-examination. Which level of prevention is this?', 'Self-exam is early detection, not prevention of the disease itself.'),
  PREV('primary', 'A nurse teaches teenagers refusal skills to avoid starting smoking. Which level of prevention is this?', 'Prevents the behavior and disease before they start.'),
  PREV('tertiary', 'A nurse teaches a client with diabetes how to inspect and care for their feet to avoid amputation. Which level of prevention is this?', 'Disease exists; the goal is to limit complications.'),
  PREV('primary', 'A community health nurse lobbies for fluoridation of the town water supply. Which level of prevention is this?', 'Prevents dental caries before they occur.'),
  PREV('secondary', 'A nurse performs tuberculin skin testing on shelter residents. Which level of prevention is this?', 'Case-finding is secondary prevention.'),
  PREV('tertiary', 'A nurse leads a cardiac rehabilitation walking group for clients after myocardial infarction. Which level of prevention is this?', 'Rehabilitation after an event.'),
  PREV('primary', 'A nurse teaches new parents about car-seat safety at a well-baby visit. Which level of prevention is this?', 'Injury prevention before anything happens.'),
  PREV('secondary', 'A nurse arranges mammograms for women over 40 at a mobile clinic. Which level of prevention is this?', 'Mammograms are the objectives\' own screening example.'),
  PREV('tertiary', 'A nurse helps a client with COPD enroll in pulmonary rehabilitation and teaches energy conservation. Which level of prevention is this?', 'Managing an established chronic illness.'),
  PREV('primary', 'A nurse distributes mosquito nets in a community where malaria is endemic. Which level of prevention is this?', 'Blocks transmission before infection.'),
  PREV('secondary', 'A nurse checks blood glucose at a health fair and refers people with high readings. Which level of prevention is this?', 'Early detection plus prompt referral.'),
  PREV('tertiary', 'A nurse teaches a client with hypertension how to take medications correctly to prevent stroke. Which level of prevention is this?', 'Hypertension already exists; preventing its complications is tertiary.'),
  Q(OBJ, 'Levels of prevention', 'Dr. Davies says community/public health nurses concentrate on which level of prevention, and why?',
    [o('Primary, because the aim is to keep people from getting sick in the first place', true, 'Straight from the objectives.'), o('Secondary, because screening is the nurse\'s main job', false, 'Nurses do all three, but focus on primary.'), o('Tertiary, because most clients already have chronic disease', false, 'No.'), o('None; all three are weighted equally', false, 'The emphasis is primary.')],
    'Nurses will do all three levels, but the concentration is on primary prevention.'),
  /* ---------- Ch. 1 ---------- */
  Q(OBJ, 'Community overview', 'Residents of a large city, adults aged 65 and older, and people without a permanent home are each examples of a:',
    [o('Population', true, 'A group in a specific area who may share traits but do not necessarily interact.'), o('Aggregate', false, 'Loosely connected people viewed as one unit, like a festival crowd.'), o('Community of solution', false, 'A group formed around one problem.'), o('Public health', false, 'That is society\'s actions to promote health.')],
    'Population = people in a place who may share traits without interacting. Aggregate = people viewed together as one unit without strong ties.'),
  Q(OBJ, 'Community overview', 'A crowd at a music festival, grouped together for the event without knowing each other, is best described as a(n):',
    [o('Aggregate', true, 'The objectives\' own example.'), o('Geographic community', false, 'Defined by shared physical space and ongoing interaction.'), o('Community of solution', false, 'United around a problem.'), o('Population', false, 'Close, but the objectives use the festival crowd for aggregate.')],
    'Aggregate: viewed together as one unit, loosely connected.'),
  Q(OBJ, 'Community overview', 'Members of a book club in different towns, fans of one sports team, and members of a medical association are examples of which type of community?',
    [o('Common-interest community', true, 'Built around shared interests regardless of location.'), o('Geographic community', false, 'Defined by physical location.'), o('Community of solution', false, 'Formed to solve a specific problem.'), o('Aggregate', false, 'No shared interest required.')],
    'Three types: geographic (place), common interest (shared interests), community of solution (a shared problem to solve).'),
  Q(OBJ, 'Community overview', 'Health professionals from several states form a group to develop strategies for improving public health. This is a:',
    [o('Community of solution', true, 'United around a cause or problem, not a place or hobby.'), o('Geographic community', false, 'They are in different places.'), o('Common-interest community', false, 'Close, but the defining feature is a specific problem to solve.'), o('Population', false, 'No.')],
    'Community of solution: people who may not share a place or hobbies but unite around a particular problem.'),
  Q(OBJ, 'Community overview', 'Which statement best contrasts acute care nursing and public health nursing?',
    [o('Acute care treats individual patients\' illnesses, usually in hospitals; public health focuses on population-level prevention, promotion and community interventions', true, 'The objectives\' distinction.'), o('Acute care prevents disease; public health treats it', false, 'Reversed.'), o('Both focus on individuals', false, 'Public health focuses on populations.'), o('Public health nursing happens only in hospitals', false, 'It is community-based.')],
    'Public health nursing: the population is the client, and prevention comes first.'),
  Q(OBJ, 'Community overview', 'Which are among the eight characteristics of community/public health nursing? Select all that apply.',
    [o('The whole population is the primary client', true, ''), o('Aim to benefit the greatest number of people', true, ''), o('Work with clients as equal partners', true, ''), o('Prioritize disease prevention', true, ''), o('Proactively reach out to those in need', true, ''), o('Treat only clients who come to the clinic', false, 'Public health nursing reaches out.'), o('Work independently of other organizations', false, 'It collaborates.')],
    'The eight: whole population as client; greatest number; equal partners; prevention; improve social, environmental and economic conditions; proactive outreach; efficient use of resources; collaboration.', { multi: true }),
  /* ---------- Ch. 2 ---------- */
  Q(OBJ, 'Core public health functions', 'Conducting health surveys to find the prevalence of chronic diseases in a community is an example of which core public health function?',
    [o('Assessment', true, 'Collect, analyze and spread information about community health.'), o('Policy development', false, 'Creating strategies from the data.'), o('Assurance', false, 'Making sure services exist and are accessible.'), o('Evaluation', false, 'Not one of the three core functions.')],
    'Assessment gathers and analyzes, policy development creates strategies, assurance makes sure services are delivered and accessible.', { fw: 'corefunctions', step: 'assessment' }),
  Q(OBJ, 'Core public health functions', 'A health department develops a smoking ban for public places and a plan to improve access to healthy foods. Which core function is this?',
    [o('Policy development', true, 'Creating strategies based on data.'), o('Assessment', false, 'Data gathering.'), o('Assurance', false, 'Service availability.'), o('Advocacy', false, 'A nurse role, not a core function.')],
    'Policy development = strategies and policies to address the concerns the assessment found.', { fw: 'corefunctions', step: 'policy' }),
  Q(OBJ, 'Core public health functions', 'Making sure there are enough providers in underserved areas and offering free screenings so essential services actually reach people is which core function?',
    [o('Assurance', true, 'Ensures services are available and accessible.'), o('Assessment', false, 'Data.'), o('Policy development', false, 'Strategy.'), o('Research', false, 'Not a core function.')],
    'Assurance closes the loop: the strategies and services are implemented and accessible.', { fw: 'corefunctions', step: 'assurance' }),
  Q(OBJ, 'Roles of the community/public health nurse', 'A nurse administers immunizations at a pharmacy clinic. Which role is this?',
    [o('Clinician', true, 'Direct care.'), o('Educator', false, 'Teaching.'), o('Advocate', false, 'Securing resources.'), o('Manager', false, 'Organizing programs.')],
    'Seven roles: clinician, educator, advocate, manager, collaborator, leader, researcher.'),
  Q(OBJ, 'Roles of the community/public health nurse', 'A nurse helps a low-income family obtain health insurance. Which role is this?',
    [o('Advocate', true, 'Ensures clients get the resources they need.'), o('Clinician', false, 'Direct care.'), o('Collaborator', false, 'Working with other organizations.'), o('Researcher', false, 'Studies.')],
    'Advocate: supports clients in getting necessary healthcare resources.'),
  Q(OBJ, 'Roles of the community/public health nurse', 'A nurse partners with schools to implement mental health programs. Which role is this?',
    [o('Collaborator', true, 'Working with other professionals and organizations.'), o('Leader', false, 'Guiding initiatives and teams.'), o('Educator', false, 'Teaching.'), o('Manager', false, 'Overseeing programs.')],
    'Collaborator = partnering with other organizations to improve community health.'),
  Q(OBJ, 'Roles of the community/public health nurse', 'Match the example to the role: managing a public vaccination campaign; leading a task force on maternal-child health; studying whether a healthy-lunch program works. In order, these are:',
    [o('Manager, leader, researcher', true, 'Each from the objectives\' examples.'), o('Leader, manager, educator', false, 'No.'), o('Collaborator, advocate, clinician', false, 'No.'), o('Researcher, manager, leader', false, 'Reversed.')],
    'Manager organizes and oversees programs; leader guides initiatives and teams; researcher studies and improves practice.'),
  Q(OBJ, 'Essential public health services', 'Which are among the ten essential public health services? Select all that apply.',
    [o('Monitor health status to identify community health problems', true, ''), o('Inform, educate and empower people about health issues', true, ''), o('Enforce laws and regulations that protect health and safety', true, ''), o('Link people to needed health services', true, ''), o('Provide all acute hospital care directly', false, 'Not an essential public health service.'), o('Sell health insurance', false, 'No.')],
    'The ten: monitor, diagnose and investigate, inform/educate/empower, mobilize partnerships, develop policies, enforce laws, link people to services, ensure a competent workforce, evaluate services, research.', { multi: true }),
  Q(OBJ, 'Practice settings', 'A nurse conducts health screenings, gives injury care and runs a wellness program for employees at a factory. Which practice setting is this?',
    [o('Occupational health', true, 'Health and safety of workers.'), o('Ambulatory services', false, 'Clinics and offices.'), o('Residential institutions', false, 'Nursing homes, assisted living.'), o('Community-at-large', false, 'Broader population initiatives.')],
    'Seven settings: home, schools, ambulatory services, occupational health, residential institutions, faith communities, community-at-large.'),
  Q(OBJ, 'Practice settings', 'A nurse offers health education and screenings to a congregation and addresses spiritual and physical health together. Which setting is this?',
    [o('Faith community', true, 'Health promotion within a religious setting.'), o('School', false, 'No.'), o('Home', false, 'No.'), o('Occupational health', false, 'No.')],
    'Faith-community nursing integrates health promotion into religious settings.'),
  Q(OBJ, 'Practice settings', 'A nurse works with the health department and non-profits to combat food insecurity and promote health equity. Which setting is this?',
    [o('Community-at-large', true, 'Broader community health initiatives and policy advocacy.'), o('Residential institution', false, 'Long-term care.'), o('Ambulatory services', false, 'Outpatient clinics.'), o('Home', false, 'No.')],
    'Community-at-large: population issues, policy advocacy, health equity.'),
  /* ---------- Ch. 5 culture ---------- */
  Q(OBJ, 'Transcultural nursing', 'Culture is best defined as:',
    [o('A shared system of beliefs, values and behavioral expectations that provides a social structure for daily living', true, 'Beliefs (what is true), values (right/wrong), behavioral expectations (how to act).'), o('A person\'s race or ethnicity', false, 'Culture is learned, not inherited.'), o('The laws of a country', false, 'No.'), o('A set of religious rules', false, 'Religion may be part of culture, not all of it.')],
    'Think of culture as the guidebook a group follows.'),
  Q(OBJ, 'Transcultural nursing', 'Which are characteristics shared by all cultures? Select all that apply.',
    [o('Learned from others', true, ''), o('Integrated system of customs and traits', true, ''), o('Shared', true, ''), o('Mostly tacit (unspoken)', true, ''), o('Dynamic: changes over time', true, ''), o('Inherited genetically', false, 'Learned, not inherited.'), o('Fixed and unchanging', false, 'Dynamic.')],
    'Learned, integrated, shared, mostly tacit, dynamic.', { multi: true }),
  Q(OBJ, 'Transcultural nursing', 'A nurse assumes her own culture\'s health practices are the only correct ones and dismisses a client\'s traditional remedy. This is:',
    [o('Ethnocentrism', true, 'Belief that one\'s own culture is superior.'), o('Cultural diversity', false, 'Presence of multiple cultures.'), o('Cultural competence', false, 'The opposite.'), o('Stereotyping', false, 'Related, but the objectives name this ethnocentrism.')],
    'Effects of ethnocentrism: communication barriers, misunderstanding of health beliefs, lower-quality care and less trust.'),
  Q(OBJ, 'Transcultural nursing', 'Why is cultural diversity significant for community/public health nursing? Select all that apply.',
    [o('Helps nurses understand and respect different health beliefs and practices', true, ''), o('Improves trust and adherence to recommendations', true, ''), o('Reduces health disparities through culturally competent care', true, ''), o('Lets nurses skip health teaching for some groups', false, 'No.'), o('Makes ethnocentrism acceptable', false, 'No.')],
    'Understanding, trust, and fewer disparities.', { multi: true }),
  Q(OBJ, 'Transcultural nursing', 'Which actions apply the principles of transcultural nursing? Select all that apply.',
    [o('Provide teaching materials in the client\'s primary language', true, ''), o('Respect culturally based family roles in decision-making', true, ''), o('Bridge cultural differences by adapting communication and care', true, ''), o('Use culturally sensitive language', true, ''), o('Insist the client adopt the nurse\'s health beliefs', false, 'Ethnocentric.'), o('Ask a child to interpret for the parents', false, 'Not culturally sensitive or safe.')],
    'Avoid ethnocentrism, bridge differences, build knowledge and skills, respect family roles, use sensitive language, teach in the client\'s language.', { multi: true }),
  /* ---------- Ch. 12 planning ---------- */
  Q(OBJ, 'Program planning', 'Put the community health planning process in order.',
    [o('Assessment → Analyze and design → Planning and implementation → Evaluation', true, 'The four stages.'), o('Planning → Assessment → Evaluation → Implementation', false, 'No.'), o('Evaluation → Assessment → Design → Implementation', false, 'No.'), o('Analyze → Assess → Implement → Evaluate', false, 'Assessment comes first.')],
    'Assess needs and resources, design evidence-based interventions with the community, implement with stakeholders, evaluate and adjust.'),
  Q(OBJ, 'Program planning', 'In a childhood obesity program, the children at risk are the ______ target population and their parents and schools are the ______ target population.',
    [o('primary; secondary', true, 'Primary = directly affected; secondary = those who influence or support them.'), o('secondary; primary', false, 'Reversed.'), o('direct; indirect', false, 'Not the course terms.'), o('host; environment', false, 'That is the epidemiologic triangle.')],
    'Primary target population is directly affected; secondary target populations influence or support the primary.'),
  Q(OBJ, 'Program planning', '"Increase public awareness about the importance of nutrition in DeKalb County" is a:',
    [o('Goal: broad and general', true, 'It sets direction without specifics.'), o('Objective: specific and measurable', false, 'No numbers, no deadline.'), o('SMART objective', false, 'No.'), o('Formative evaluation', false, 'No.')],
    'Goals are broad; objectives are specific, measurable steps toward the goal.'),
  Q(OBJ, 'Program planning', 'Which statement is a complete SMART objective?',
    [o('"By February 26, attendees will identify three healthy alternatives to fast food during a local health class."', true, 'Specific, measurable, achievable, relevant, timely: the objectives\' own example.'), o('"Promote health in the community."', false, 'Not specific or measurable.'), o('"Reduce smoking someday."', false, 'No measure, no deadline.'), o('"Hold workshops."', false, 'How many? By when?')],
    'SMART: Specific, Measurable, Achievable, Relevant, Timely.'),
  Q(OBJ, 'Program planning', 'Checking participant feedback halfway through a nutrition class and adjusting the approach is which type of evaluation?',
    [o('Formative (process) evaluation', true, 'Conducted during the program to refine it.'), o('Summative (outcome) evaluation', false, 'After completion, to judge effectiveness.'), o('Needs assessment', false, 'Before the program.'), o('Impact analysis', false, 'Not the course term.')],
    'Formative = during, to refine. Summative = after, to judge results.'),
  Q(OBJ, 'Program planning', 'Comparing obesity rates before and after a year-long intervention to judge how well it worked is:',
    [o('Summative (outcome) evaluation', true, 'After completion, measuring effectiveness.'), o('Formative (process) evaluation', false, 'That happens during the program.'), o('Assessment', false, 'That is the first planning stage.'), o('A SMART objective', false, 'No.')],
    'Summative evaluation measures outcomes at the end.'),
  Q(OBJ, 'Program planning', 'A teenager drinks more because he believes alcohol increases social acceptance. Which factor influencing behavior change is this?',
    [o('Predisposing factor', true, 'Internal beliefs, attitudes, values.'), o('Reinforcing factor', false, 'Social influence from family, peers, norms.'), o('Enabling factor', false, 'External resources, access, policies.'), o('Environmental factor', false, 'Not the course term.')],
    'PRE: Predisposing (inside the person), Reinforcing (people around them), Enabling (resources and access).'),
  Q(OBJ, 'Program planning', 'A person keeps smoking because his friends smoke together socially. Which factor is this?',
    [o('Reinforcing factor', true, 'Social influence from peers.'), o('Predisposing factor', false, 'Internal beliefs.'), o('Enabling factor', false, 'External resources or policies.'), o('Primary prevention', false, 'No.')],
    'Reinforcing factors come from family, peers and societal norms.'),
  Q(OBJ, 'Program planning', 'A low-income neighborhood with no grocery store selling fresh produce encourages unhealthy eating. Which factor is this?',
    [o('Enabling factor', true, 'External resources, accessibility, policies.'), o('Predisposing factor', false, 'Beliefs and attitudes.'), o('Reinforcing factor', false, 'Social influence.'), o('Host factor', false, 'Epidemiology term.')],
    'Enabling factors are the external conditions that make a behavior easier or harder.'),
  /* ---------- Ch. 15 community as client ---------- */
  Q(OBJ, 'Community as client', 'Morbidity and mortality rates, mental health resources, crime rates and support networks describe which dimension of the community as a client?',
    [o('Status: the physical, emotional and social health of the community', true, 'Physical, emotional and social status.'), o('Structure: services, resources and systems', false, 'Hospitals, clinics, schools.'), o('Process: relationships and interactions', false, 'How members relate.'), o('Assets', false, 'A type of assessment.')],
    'Three dimensions: status (health), structure (services and systems), process (relationships).'),
  Q(OBJ, 'Community as client', 'The number of hospitals, clinics, schools and public services in a town describes which dimension?',
    [o('Structure', true, 'Availability of services, resources and systems.'), o('Status', false, 'Health of the community.'), o('Process', false, 'Interactions among members.'), o('Assurance', false, 'A core function.')],
    'Structure = what exists to support the community.'),
  Q(OBJ, 'Community as client', 'Which are characteristics of a healthy community (Healthy People 2030)? Select all that apply.',
    [o('Promotes living free of preventable disease and early death', true, ''), o('Eliminates health disparities and promotes health equity', true, ''), o('Engages leaders and residents in decision-making', true, ''), o('Encourages public and private collaboration for health', true, ''), o('Relies on hospitals alone to keep people healthy', false, 'No.'), o('Limits health improvement to one life stage', false, 'All life stages.')],
    'Also: environments that support well-being, and healthy development across all life stages.', { multi: true }),
  Q(OBJ, 'Community as client', 'Addressing diabetes in a Hispanic community by improving access to healthy foods and culturally appropriate care illustrates:',
    [o('Community as client: population-based intervention considering social determinants and environment', true, 'The objectives\' example.'), o('Acute care nursing', false, 'Individual focus.'), o('Tertiary prevention only', false, 'Not the point.'), o('A windshield survey', false, 'That is an assessment method.')],
    'Community as client = the group, not the individual, is the focus of intervention.'),
  Q(OBJ, 'Community assessment', 'A nurse drives and walks through a neighborhood observing housing, parks, traffic and where people gather. Which type of community assessment is this?',
    [o('Windshield survey', true, 'Observation while moving through the community.'), o('Problem-oriented assessment', false, 'Targets one specific health problem.'), o('Comprehensive assessment', false, 'Broad evaluation of all aspects.'), o('Community assets assessment', false, 'Strengths and resources.')],
    'Five types: windshield survey, problem-oriented, community-subsystem, comprehensive, community assets.'),
  Q(OBJ, 'Community assessment', 'A nurse investigates why diabetes rates are high in one county, looks for root causes and designs targeted interventions. Which type of assessment is this?',
    [o('Problem-oriented assessment', true, 'Focused on a specific health problem.'), o('Windshield survey', false, 'Observation.'), o('Community-subsystem assessment', false, 'One sector, such as schools or transportation.'), o('Comprehensive assessment', false, 'All aspects.')],
    'Problem-oriented: one problem, its causes, its solutions.'),
  Q(OBJ, 'Community assessment', 'Identifying a community\'s strengths, resources and capabilities that can be leveraged to solve problems is a:',
    [o('Community assets assessment', true, 'Focuses on positives that can be used.'), o('Comprehensive assessment', false, 'Everything, not just strengths.'), o('Problem-oriented assessment', false, 'Problems.'), o('Subsystem assessment', false, 'One sector.')],
    'Assets assessment looks at what the community has, not what it lacks.'),
  Q(OBJ, 'Community assessment', 'Which are methods of conducting a community health assessment? Select all that apply.',
    [o('Surveys', true, ''), o('Descriptive epidemiologic studies', true, ''), o('Geographic information system (GIS) mapping', true, ''), o('Community forums such as town halls', true, ''), o('Focus groups', true, ''), o('Randomized drug trials', false, 'Experimental epidemiology, not community assessment.')],
    'Surveys, descriptive epi studies, GIS, forums, focus groups.', { multi: true }),
  Q(OBJ, 'Community assessment', 'A nurse conducts her own door-to-door survey of residents. The results are:',
    [o('Primary data: collected directly by the researcher', true, 'Surveys and observations you do yourself.'), o('Secondary data: pre-existing records', false, 'Government reports, health records, statistics.'), o('National data', false, 'Census, CDC.'), o('International data', false, 'Global organizations.')],
    'Primary = you collected it. Secondary = someone already collected it.'),
  Q(OBJ, 'Community assessment', 'Which are sources of community data? Select all that apply.',
    [o('Primary data (surveys, observations)', true, ''), o('Secondary data (government reports, health records)', true, ''), o('National data (U.S. Census Bureau, CDC reports)', true, ''), o('International data (global health organizations)', true, ''), o('Local, community-specific data', true, ''), o('Guesses by the planning team', false, 'Not data.')],
    'Five sources: primary, secondary, international, national, local.', { multi: true }),
  /* ---------- Ch. 7 epidemiology ---------- */
  Q(OBJ, 'Epidemiologic triangle', 'For malaria, the Plasmodium parasite, humans, and a warm humid climate where mosquitoes thrive are, in order, the:',
    [o('Agent, host, environment', true, 'The objectives\' malaria example.'), o('Host, agent, environment', false, 'Reversed.'), o('Vector, host, agent', false, 'The mosquito is the vector.'), o('Reservoir, portal, host', false, 'Chain of infection terms.')],
    'Agent = cause; host = who gets it; environment = conditions that let it spread. Vectors (mosquitoes) carry the agent between hosts.'),
  Q(OBJ, 'Epidemiologic triangle', 'A nurse teaching daycare employees about the epidemiologic triangle should include which factors as AGENTS? Select all that apply.',
    [o('Toxins', true, 'Chemical agent.'), o('Bacteria', true, 'Biological agent.'), o('Resource availability', false, 'Environment.'), o('Ethnicity', false, 'Host characteristic.'), o('Altered immunity', false, 'Host characteristic.')],
    'The objectives\' practice question: agents cause disease (biological, chemical, physical, nutritional). Ethnicity and immunity describe the host.', { multi: true }),
  Q(OBJ, 'Causality', '"Smoking → lung damage → lung cancer" illustrates which theory of causality?',
    [o('Chain of causation', true, 'A linear sequence.'), o('Web of causation', false, 'Multiple interconnected factors.'), o('Epidemiologic triangle', false, 'Agent, host, environment.'), o('Natural history of disease', false, 'Stages over time.')],
    'Chain = one thing leads to the next. Web = many interconnected factors (heart disease: diet, genetics, exercise, stress, smoking).'),
  Q(OBJ, 'Basic epidemiology', 'The person-place-time model asks:',
    [o('Who is affected, where the disease occurs, and when it occurs', true, 'Age/sex/status; location/climate; season/trend.'), o('What the agent is, who the host is, what the environment is', false, 'Triangle.'), o('How the germ leaves and enters', false, 'Chain of infection.'), o('Whether the disease is endemic or epidemic', false, 'Disease patterns.')],
    'Person, place, time: the descriptive questions of epidemiology.'),
  Q(OBJ, 'Chain of transmission', 'Put the six links of the chain of transmission in order.',
    [o('Infectious agent → reservoir → portal of exit → means of transmission → portal of entry → susceptible host', true, 'Germ, where it lives, how it leaves, how it travels, how it enters, who it infects.'), o('Reservoir → agent → host → exit → entry → transmission', false, 'No.'), o('Host → agent → reservoir → transmission', false, 'No.'), o('Agent → host → reservoir → portal of exit', false, 'No.')],
    'Break any one link and transmission stops: that is the logic behind hand hygiene, masks and isolation.'),
  Q(OBJ, 'Chain of transmission', 'Shaking hands with or kissing an infected person is which mode of transmission?',
    [o('Direct transmission', true, 'Person-to-person contact.'), o('Indirect transmission', false, 'Via contaminated objects.'), o('Airborne transmission', false, 'Tiny droplets carried in the air.'), o('Vector transmission', false, 'Living carrier.')],
    'Direct = contact. Indirect = object (vehicle). Airborne = inhaled droplets. Vector = living carrier such as a mosquito.'),
  Q(OBJ, 'Chain of transmission', 'Touching a doorknob contaminated by an infected person and then rubbing your eyes is which mode of transmission?',
    [o('Indirect transmission', true, 'Through a contaminated surface or object.'), o('Direct transmission', false, 'Person-to-person.'), o('Airborne', false, 'Inhaled.'), o('Vector-borne', false, 'Living carrier.')],
    'Indirect transmission happens through contaminated surfaces, utensils or shared equipment.'),
  Q(OBJ, 'Immunity', 'A newborn is protected by antibodies received through the placenta and breast milk. This is:',
    [o('Natural passive immunity', true, 'Borrowed antibodies, temporary.'), o('Natural active immunity', false, 'Body makes its own after infection.'), o('Artificial active immunity', false, 'Vaccine.'), o('Herd immunity', false, 'Community-level protection.')],
    'Passive = borrowed and short-lived. Active = made by your own immune system and long-lasting. Natural = from life; artificial = from medicine.'),
  Q(OBJ, 'Immunity', 'Immunity to cowpox also protecting a person against smallpox is an example of:',
    [o('Cross-immunity', true, 'Immunity to one pathogen protects against a similar one.'), o('Herd immunity', false, 'Community protection.'), o('Passive immunity', false, 'Borrowed antibodies.'), o('Active immunity', false, 'Close, but the specific concept is cross-immunity.')],
    'The objectives\' own example of cross-immunity.'),
  Q(OBJ, 'Immunity', 'When a large portion of a community is immune, spread becomes unlikely and non-immune people are protected. This is:',
    [o('Herd immunity', true, 'Population-level protection.'), o('Cross-immunity', false, 'Related pathogens.'), o('Passive immunity', false, 'Borrowed.'), o('Active immunity', false, 'Individual.')],
    'Herd immunity is why high vaccination coverage protects people who cannot be vaccinated.'),
  Q(OBJ, 'Natural history of disease', 'Match the stage to the prevention level: susceptibility, subclinical disease, clinical disease.',
    [o('Primary, secondary, tertiary', true, 'Prevent before exposure; detect during incubation; treat and rehabilitate once symptomatic.'), o('Tertiary, secondary, primary', false, 'Reversed.'), o('Secondary, primary, tertiary', false, 'No.'), o('Primary, primary, secondary', false, 'No.')],
    'Four stages: susceptibility (before exposure), subclinical (after exposure, before symptoms: incubation), clinical (symptoms, diagnosis, treatment), recovery/disability/death.'),
  Q(OBJ, 'Natural history of disease', 'During which stage would the community health nurse FIRST expect to see signs of a disease via laboratory testing?',
    [o('Subclinical disease stage', true, 'After exposure, before symptoms, labs can already detect it (the objectives\' reasoning).'), o('Susceptibility stage', false, 'No exposure yet; nothing to detect.'), o('Clinical disease stage', false, 'Signs are already visible without labs.'), o('Resolution stage', false, 'Only evidence of past infection.')],
    'The objectives note the slide said clinical, but reason it through: labs first detect disease in the subclinical stage.'),
  /* ---------- Rates: definitions and the worked class examples ---------- */
  Q(OBJ, 'Epidemiologic rates', 'Which statement correctly distinguishes incidence from prevalence?',
    [o('Incidence counts NEW cases in a time period; prevalence counts ALL existing cases at a point in time', true, 'The key word for incidence is "new".'), o('Incidence counts deaths; prevalence counts cases', false, 'No.'), o('They are the same', false, 'No.'), o('Prevalence counts new cases', false, 'Reversed.')],
    'Incidence = new. Prevalence = existing.'),
  Q(OBJ, 'Epidemiologic rates', 'Match the definition: total deaths regardless of cause; deaths from one cause; deaths among people who have a specific disease.',
    [o('Crude mortality, cause-specific mortality, case fatality', true, ''), o('Case fatality, crude mortality, cause-specific', false, 'No.'), o('Cause-specific, case fatality, crude', false, 'No.'), o('Morbidity, mortality, attack rate', false, 'No.')],
    'Crude = all deaths ÷ population. Cause-specific = deaths from that cause ÷ population. Case fatality = deaths from the disease ÷ people who have the disease (× 100, a percent).'),
  Q(OBJ, 'Epidemiologic rates', 'Springhill (population 452,780) reported 95 new AIDS cases in 1991. What is the 1991 incidence rate per 100,000?',
    [o('21 per 100,000', true, '95 ÷ 452,780 × 100,000 = 20.98.'), o('56 per 100,000', false, 'That is the prevalence from the same class problem.'), o('2.1 per 100,000', false, 'Wrong multiplier.'), o('188 per 100,000', false, 'Used the wrong numerator.')],
    'Incidence = new cases ÷ population × 100,000. The class worked example.'),
  Q(OBJ, 'Epidemiologic rates', 'Springhill: 850 total AIDS cases reported 1981–1991, 595 deaths from AIDS 1981–1990, population 452,780. What is the December 31, 1991 prevalence per 100,000?',
    [o('56 per 100,000', true, '(850 − 595) = 255 living cases ÷ 452,780 × 100,000 = 56.3.'), o('188 per 100,000', false, 'Forgot to subtract the deaths.'), o('21 per 100,000', false, 'That is the incidence.'), o('131 per 100,000', false, 'Used deaths as the numerator.')],
    'Prevalence counts existing cases, so people who died are not included: subtract deaths from total cases first.'),
  Q(OBJ, 'Epidemiologic rates', 'Springhill had 10 infant deaths and 300 live births in the past year. What is the infant mortality rate?',
    [o('33 per 1,000 live births', true, '10 ÷ 300 × 1,000 = 33.3.'), o('3.3 per 1,000', false, 'Wrong multiplier.'), o('2.2 per 100,000 population', false, 'IMR uses live births, not population.'), o('30 per 1,000', false, 'Arithmetic.')],
    'Infant mortality rate = infant deaths (under 1 year) ÷ live births × 1,000. Always live births as the denominator.'),
  Q(OBJ, 'Epidemiologic rates', 'A Haitian city (population 359,451) had 20,000 deaths in 2011, including 10,000 from cholera; 150,000 people had cholera. What is the crude mortality rate per 100,000?',
    [o('5,564 per 100,000', true, '20,000 ÷ 359,451 × 100,000.'), o('2,782 per 100,000', false, 'That is the cholera cause-specific rate.'), o('6.7%', false, 'That is the case fatality rate.'), o('13.3 per 100,000', false, 'Wrong numbers.')],
    'Crude mortality = all deaths ÷ population × 10ⁿ, no matter the cause.'),
  Q(OBJ, 'Epidemiologic rates', 'Same city: what is the cause-specific mortality rate from cholera per 100,000?',
    [o('2,782 per 100,000', true, '10,000 cholera deaths ÷ 359,451 × 100,000.'), o('5,564 per 100,000', false, 'Crude rate.'), o('6.7 per 100,000', false, 'Case fatality is a percent of cases, not a population rate.'), o('41,730 per 100,000', false, 'Used cases as the numerator.')],
    'Cause-specific mortality = deaths from that cause ÷ total population.'),
  Q(OBJ, 'Epidemiologic rates', 'Same city: what is the case fatality rate from cholera?',
    [o('6.7%', true, '10,000 deaths ÷ 150,000 cases × 100.'), o('2,782 per 100,000', false, 'Cause-specific mortality.'), o('50%', false, 'Wrong denominator.'), o('0.067 per 1,000', false, 'Case fatality is expressed as a percent.')],
    'Case fatality = deaths from the disease ÷ people WITH the disease × 100. The denominator is cases, not population.'),
  Q(OBJ, 'Epidemiologic rates', 'At a restaurant, 84 people ate contaminated lettuce and 13 developed E. coli infection. What is the attack rate?',
    [o('15%', true, '13 ÷ 84 × 100 = 15.5, rounded to 15.'), o('1.5%', false, 'Wrong multiplier.'), o('646 per 100,000', false, 'Attack rate uses the exposed group and a percent.'), o('84%', false, 'Reversed.')],
    'Attack rate = people exposed who got sick ÷ total exposed × 100.'),
  Q(OBJ, 'Epidemiologic rates', 'When calculating a rate for cervical cancer, which population belongs in the denominator?',
    [o('Women only, because men have no cervix', true, 'The objectives\' reminder: watch the population at risk.'), o('The whole population', false, 'Overstates the denominator.'), o('Women over 65 only', false, 'No.'), o('Only women who were screened', false, 'No.')],
    'Pay attention to the cause: the denominator is the population at risk.'),
  Q(OBJ, 'Epidemiologic studies', 'Comparing people who have lung cancer with people who do not, to see whether smoking is more common among the cases, is a:',
    [o('Case-control study', true, 'Cases versus controls, looking back for exposures.'), o('Cohort study', false, 'Follows a group forward over time.'), o('Prevalence study', false, 'How common a disease is right now.'), o('Experimental study', false, 'Researchers assign an intervention.')],
    'Analytic epidemiology: prevalence studies (how common now), case-control (compare cases to controls), cohort (follow groups over time). Experimental = trials.'),
  Q(OBJ, 'Epidemiologic studies', 'Tracking a group of smokers and non-smokers for 10 years to see who develops heart disease is a:',
    [o('Cohort study', true, 'Follows groups forward in time.'), o('Case-control study', false, 'Starts with disease and looks back.'), o('Prevalence study', false, 'Snapshot.'), o('Clinical trial', false, 'Assigns an intervention.')],
    'Cohort = forward in time from exposure to outcome.'),
  Q(OBJ, 'Epidemiologic studies', 'Which are sources of epidemiologic information? Select all that apply.',
    [o('Vital statistics (births, deaths, marriages)', true, ''), o('Census data', true, ''), o('Reportable diseases and disease registries', true, ''), o('Surveillance systems', true, ''), o('Environmental monitoring', true, ''), o('Social media rumors', false, 'Not a recognized source.')],
    'Also: NCHS health surveys, federal agency reports, observational and scientific studies, simple counts.', { multi: true }),

  /* ---------- Epidemiology Q&A (25 keyed questions) ---------- */
  Q(EPI, 'Epidemiologic triangle', 'When discussing influenza with college students, the nurse focuses on the three aspects of the epidemiologic triangle. What would be included?',
    [o('The influenza A virus, student housing, and students on campus', true, 'Agent, environment, host.'), o('The influenza A virus, hand washing, and antivirals', false, 'Interventions, not the triangle.'), o('Students on campus, their families, and their professors', false, 'All hosts.'), o('Student housing, dining halls, and lecture halls', false, 'All environment.')],
    'Agent = the virus, host = the students, environment = the housing.'),
  Q(EPI, 'Disease patterns', 'Malaria surveillance over 20 years shows a constant level of malaria in Nicaragua. This is:',
    [o('Endemic', true, 'Consistently present at an expected baseline.'), o('Epidemic', false, 'A sudden increase above baseline.'), o('Pandemic', false, 'Spread across countries or continents.'), o('Sporadic', false, 'Occasional, irregular cases.')],
    'Endemic = steady baseline. Epidemic = above baseline. Pandemic = worldwide.'),
  Q(EPI, 'Modes of transmission', 'West Nile virus is most often transmitted to humans by mosquitoes. What type of transmission is this?',
    [o('Vector', true, 'A living organism carries the agent between hosts.'), o('Direct contact', false, 'Person to person.'), o('Airborne', false, 'Inhaled droplets.'), o('Vehicle', false, 'An inanimate object.')],
    'Vector = living carrier, usually an arthropod.'),
  Q(EPI, 'Modes of transmission', 'A patient contracted cutaneous anthrax by handling sheep fur infected with anthrax. What type of transmission is this?',
    [o('Indirect transmission through a vehicle', true, 'The fur is an inanimate object carrying spores.'), o('Direct transmission', false, 'No infected person or animal touched him directly.'), o('Vector transmission', false, 'A vector is alive.'), o('Airborne transmission', false, 'Not inhaled here.')],
    'Vehicle = inanimate object (fur, food, syringe). Vector = living organism.'),
  Q(EPI, 'Immunity', 'Which is an example of artificial passive immunity?',
    [o('Receiving an IM injection of immune globulin to prevent hepatitis A', true, 'Antibodies given medically.'), o('Antibodies crossing the placenta', false, 'Natural passive.'), o('Antibodies in breast milk', false, 'Natural passive.'), o('Recovering from the disease', false, 'Natural active.')],
    'Passive = antibodies given, not made. Artificial = administered medically.'),
  Q(EPI, 'Disease patterns', 'An instructor discusses the worldwide distribution of AIDS. This situation should be categorized as a(n):',
    [o('Pandemic', true, 'Spread across multiple countries and continents.'), o('Endemic', false, 'Steady in one region.'), o('Epidemic', false, 'Above baseline in one population.'), o('Outbreak', false, 'Localized cluster.')],
    'Worldwide = pandemic.'),
  Q(EPI, 'Modes of transmission', 'The community health nurse discusses the role of a vector in disease spread. To which is the nurse most likely referring?',
    [o('A mosquito', true, 'A living organism that carries and transmits a pathogen.'), o('Contaminated meat', false, 'A vehicle.'), o('A used syringe', false, 'A vehicle.'), o('An infected person', false, 'A reservoir.')],
    'Vector = living carrier. Objects are vehicles; infected people are reservoirs.'),
  Q(EPI, 'Immunity', 'The nurse educator knows a student understands immunity when the student states:',
    [o('"Active immunity is long term and can be attained via vaccines."', true, 'The body makes its own antibodies after infection or vaccination.'), o('"Passive immunity lasts a lifetime."', false, 'Passive is short-lived.'), o('"Vaccines give passive immunity."', false, 'Vaccines give active immunity.'), o('"Maternal antibodies give the infant active immunity."', false, 'That is passive.')],
    'Active = your own antibodies, long-lasting. Passive = borrowed, temporary.'),
  Q(EPI, 'Chain of infection', 'A client with rhinovirus symptoms sneezes near a nurse, who develops the same symptoms two days later. What is the reservoir for the rhinovirus?',
    [o('The client', true, 'Where the pathogen lives and multiplies.'), o('The sneeze', false, 'That is the mode of transmission.'), o('The nurse', false, 'The new host.'), o('The air in the room', false, 'Not where it multiplies.')],
    'Reservoir = where the germ lives and grows. Here, the infected client.'),
  Q(EPI, 'Chain of infection', 'In the same scenario, what was the portal of exit of the rhinovirus?',
    [o('The secretions from the client\'s nose', true, 'How the pathogen left the reservoir.'), o('The nurse\'s mouth', false, 'That would be a portal of entry.'), o('The client\'s hands', false, 'Not the route here.'), o('The client\'s skin', false, 'No.')],
    'Portal of exit = the route out of the reservoir. Respiratory secretions for a respiratory virus.'),
  Q(EPI, 'Chain of infection', 'In the same scenario, what mode of transmission is depicted?',
    [o('Direct transmission: droplet', true, 'Droplets went straight from the client to the nurse with no object in between.'), o('Indirect transmission: vehicle', false, 'No object.'), o('Vector transmission', false, 'No living carrier.'), o('Airborne transmission', false, 'Airborne is tiny particles suspended in air; a sneeze at close range is droplet.')],
    'Direct droplet: the sneeze traveled directly to the susceptible host.'),
  Q(EPI, 'Natural history of disease', 'A miner is bitten by a bat, develops a rash and headache weeks later, and is then diagnosed with rabies. At which point did the subclinical period (stage 2) most likely begin?',
    [o('After exposure from the bat bite', true, 'Subclinical begins at exposure and runs silently through incubation.'), o('When the rash and headache started', false, 'That begins the clinical stage.'), o('When the diagnosis was made', false, 'Clinical stage.'), o('When the miner entered the cave', false, 'Still susceptibility, before exposure.')],
    'Subclinical = after exposure, before symptoms.'),
  Q(EPI, 'Natural history of disease', 'In the same scenario, when did clinical disease (stage 3) begin?',
    [o('With the onset of symptoms (the rash and headache)', true, 'Clinical disease = recognizable signs and symptoms.'), o('With the bat bite', false, 'Exposure begins the subclinical stage.'), o('With the formal diagnosis', false, 'Diagnosis happens during the clinical stage, not at its start.'), o('With recovery', false, 'Stage 4.')],
    'Clinical disease starts when symptoms appear, not when a doctor names it.'),
  Q(EPI, 'Epidemiologic rates', 'Which statement is true about incidence and prevalence?',
    [o('Incidence is the number of new cases of a disease or health condition', true, 'Key word: new.'), o('Prevalence counts only new cases', false, 'Prevalence counts all existing cases.'), o('Incidence measures mortality', false, 'No.'), o('Prevalence measures deaths', false, 'No.')],
    'Incidence = new. Prevalence = existing or all.'),
  Q(EPI, 'Causality', 'The nurse examines the possibility that multiple factors are involved in the development of cerebral palsy. Which concept is the nurse applying?',
    [o('Web of causation', true, 'Many interacting factors, not one cause.'), o('Chain of causation', false, 'A single linear sequence.'), o('Epidemiologic triangle', false, 'Agent, host, environment.'), o('Herd immunity', false, 'No.')],
    'Web of causation fits chronic and developmental conditions with many contributing factors.'),
  Q(EPI, 'Epidemiologic rates', 'Madison County 2017: population 25,578; 75 new cardiovascular disease cases. What is the CVD incidence rate per 10,000?',
    [o('29.32 per 10,000', true, '75 ÷ 25,578 × 10,000.'), o('2.93 per 10,000', false, 'Wrong multiplier.'), o('293.2 per 10,000', false, 'Wrong multiplier.'), o('0.29 per 10,000', false, 'Forgot the multiplier.')],
    'Incidence = new cases ÷ population × 10,000.'),
  Q(EPI, 'Epidemiologic rates', 'Madison County 2017: 56 lung cancer deaths; population 25,578. What is the cause-specific mortality rate for lung cancer per 10,000?',
    [o('21.89 per 10,000', true, '56 ÷ 25,578 × 10,000.'), o('316.29 per 10,000', false, 'That is the crude mortality rate.'), o('2.19 per 10,000', false, 'Wrong multiplier.'), o('56 per 10,000', false, 'Not divided by the population.')],
    'Cause-specific mortality isolates deaths from one condition.'),
  Q(EPI, 'Epidemiologic rates', 'Madison County 2017: 22 new breast cancer cases; population 25,578. Incidence rate per 10,000?',
    [o('8.60 per 10,000', true, '22 ÷ 25,578 × 10,000.'), o('0.86 per 10,000', false, 'Wrong multiplier.'), o('86.0 per 10,000', false, 'Wrong multiplier.'), o('4.69 per 10,000', false, 'That is testicular cancer.')],
    'Same formula, different numerator.'),
  Q(EPI, 'Epidemiologic rates', 'Madison County 2017: 12 new testicular cancer cases; population 25,578. Incidence rate per 10,000?',
    [o('4.69 per 10,000', true, '12 ÷ 25,578 × 10,000.'), o('8.60 per 10,000', false, 'Breast cancer.'), o('0.47 per 10,000', false, 'Wrong multiplier.'), o('46.9 per 10,000', false, 'Wrong multiplier.')],
    'Note the quiz used the total population as the denominator here; the objectives remind you to think about the population at risk when the question asks for it.'),
  Q(EPI, 'Epidemiologic rates', 'Madison County 2017: 809 total deaths; population 25,578. Crude mortality rate per 10,000?',
    [o('316.29 per 10,000', true, '809 ÷ 25,578 × 10,000.'), o('21.89 per 10,000', false, 'Lung cancer cause-specific rate.'), o('31.63 per 10,000', false, 'Wrong multiplier.'), o('12.48 per 10,000', false, 'Infant mortality.')],
    'Crude mortality uses ALL deaths.'),
  Q(EPI, 'Epidemiologic rates', 'Madison County 2017: 15 infant deaths; 1,202 live births. Infant mortality rate?',
    [o('12.48 per 1,000 live births', true, '15 ÷ 1,202 × 1,000.'), o('5.86 per 10,000 population', false, 'IMR uses live births, not population.'), o('1.25 per 1,000', false, 'Wrong multiplier.'), o('124.8 per 1,000', false, 'Wrong multiplier.')],
    'Infant mortality always uses live births as the denominator and a multiplier of 1,000.'),
  Q(EPI, 'Epidemiologic rates', 'Madison County 2017: 1,202 live births; population 25,578. Birth rate?',
    [o('46.99 per 1,000 population', true, '1,202 ÷ 25,578 × 1,000.'), o('469.9 per 10,000', false, 'Birth rate conventionally uses 1,000.'), o('4.70 per 1,000', false, 'Wrong multiplier.'), o('12.48 per 1,000', false, 'Infant mortality.')],
    'Birth rate = live births ÷ population × 1,000.'),

  /* ---------- NURS 4510 Study Guide (25 keyed questions) ---------- */
  Q(SG, 'Family assessment', 'A community health nurse is collecting data about a family\'s demographics. Which data would the nurse include? Select the 3 that apply.',
    [o('Socioeconomic status', true, 'Core demographic characteristic.'), o('Ethnicity', true, 'Demographic.'), o('Education of members', true, 'Demographic.'), o('Housing', false, 'Environmental.'), o('Dietary patterns', false, 'Lifestyle.'), o('Climate', false, 'Environmental.')],
    'Demographics = population characteristics: socioeconomic status, ethnicity/race, education. Housing, diet and climate are environment or lifestyle.', { multi: true }),
  Q(SG, 'Family nursing', 'A community health nurse is attempting to empower a family to become independent. Which action is most appropriate?',
    [o('Build on the family\'s strengths', true, 'Reinforce what they already do well.'), o('Do for the family what they are not able to do', false, 'Creates dependence.'), o('Focus attention on the problem areas', false, 'Deficit focus.'), o('Extend the length of nursing visits', false, 'Not empowerment.')],
    'Empowerment = strengths, not deficits (asked twice in the study guide: Q3 and Q15).'),
  Q(SG, 'Family nursing', 'Families demonstrate attributes as social systems. Which attribute should the nurse keep in mind?',
    [o('Each member\'s actions affect the other members', true, 'Systems theory: interdependence.'), o('Families are rigid and never change', false, 'They change constantly.'), o('Family members are independent groups', false, 'Interdependent.'), o('Family structures lack goal direction', false, 'No.')],
    'A change affecting one member ripples through the whole family.'),
  Q(SG, 'Family nursing', 'Which statement indicates the importance of roles within a family?',
    [o('Selection of specific roles depends on the family\'s structure, needs and patterns of functioning', true, 'Roles are flexible and context-shaped.'), o('Family roles are restricted to the immediate family', false, 'No.'), o('Roles are determined by those outside the family', false, 'No.'), o('Family members can play only one role at a time', false, 'No.')],
    'Roles are shaped by the family\'s own context, not fixed or externally imposed.'),
  Q(SG, 'Family nursing', 'A nurse informally teaches groups of parents about typical childhood developmental milestones. Which modality is this?',
    [o('Anticipatory guidance', true, 'Preparing families for expected changes ahead of time.'), o('Lecture', false, 'Formal.'), o('Demonstration', false, 'Showing a skill.'), o('Visual images', false, 'A tool, not the modality.')],
    'Anticipatory guidance = teaching about what is coming next developmentally.'),
  Q(SG, 'Family nursing', 'The Bakers make sure their young children spend time with grandparents, aunts and uncles and attend the annual family reunion. Which family function is met?',
    [o('Affiliation', true, 'Belonging and ties to the broader kin network.'), o('Security and acceptance', false, 'Different function.'), o('Identity', false, 'Different function.'), o('Affection', false, 'Different function.')],
    'Affiliation = connectedness with extended family.'),
  Q(SG, 'Family nursing', 'When planning care for several families, which consideration is most important?',
    [o('Family structure can change at any time during the interaction', true, 'Structures are dynamic and diverse.'), o('Structure has minimal impact on the support families need', false, 'It matters.'), o('Traditional family structures are the common norm', false, 'Not an assumption to make.'), o('Issues are the same regardless of structure', false, 'No.')],
    'Stay adaptable; never assume a static or "traditional" structure.'),
  Q(SG, 'Family nursing', 'Which action reflects using the family developmental (life-cycle) framework?',
    [o('Adapt interventions to the family\'s stage of development', true, 'The study guide\'s marked answer.'), o('Use the same interventions for every family', false, 'No.'), o('Focus only on the oldest member', false, 'No.'), o('Delay interventions until the family asks', false, 'No.')],
    'Individualize care to where the family is in its life cycle.'),
  Q(SG, 'Family assessment', 'Why is a family assessment important on a first visit?',
    [o('It gives the nurse a better understanding of how family characteristics affect the family\'s safety and well-being', true, 'The clinical purpose.'), o('It provides a legal basis for interventions', false, 'No.'), o('It alleviates the nurse\'s concerns', false, 'No.'), o('Regulations require documentation for all families', false, 'Not the reason.')],
    'Assess to understand, so care is safe and individualized.'),
  Q(SG, 'Family assessment', 'Which family statement reflects the family\'s unique values?',
    [o('"Family problems stay within the family."', true, 'A value the family generated.'), o('"Everyone must wear seat belts."', false, 'External rule.'), o('"Report cards come out on Friday."', false, 'A fact.'), o('"School attendance is mandatory."', false, 'External rule.')],
    'Values come from the family itself; laws and schedules do not.'),
  Q(SG, 'Family nursing', 'A home health nurse plans to interview each family member to see how they might help a client recover after a stroke. Which approach to family health is this?',
    [o('Family as a system', true, 'Each member contributes to the whole.'), o('Family as context', false, 'Family is background to the individual.'), o('Family as a client', false, 'The family unit itself is the patient.'), o('Family as a component of society', false, 'Family within the larger community.')],
    'Interviewing everyone about how they affect the client\'s recovery = the family as an interconnected system.'),
  Q(SG, 'Family nursing', 'During a home visit, a visiting older relative who has been drinking becomes verbally abusive and loud. Which action is best?',
    [o('Ask the sober family members to take the visitor home', true, 'Handles the safety risk and lets the visit continue.'), o('Terminate the visit and reschedule', false, 'Loses the visit unnecessarily.'), o('Suggest the relative take a nap in another room', false, 'Does not resolve the risk.'), o('Continue the visit with caution', false, 'Unsafe.')],
    'Address the safety problem directly while keeping the client\'s care going.'),
  Q(SG, 'Family nursing', 'Which is true of families?',
    [o('Families are constantly changing through the life cycle, requiring adaptation', true, 'Predictable developmental stages.'), o('Responsibility rests on the head of the household', false, 'No.'), o('Roles of family members never change', false, 'They change.'), o('The family\'s developmental stage does not affect roles', false, 'It does.')],
    'Families evolve; roles and responsibilities adapt.'),
  Q(SG, 'Family nursing', 'New parents are anxious and unsure about feeding schedules and infant care. Which is the most appropriate initial intervention?',
    [o('Assess the parents\' current knowledge and understanding of newborn care', true, 'Assessment comes first.'), o('Provide written instructions', false, 'Teaching before assessing.'), o('Refer to a pediatrician for education', false, 'Referral before assessing.'), o('Encourage parenting classes', false, 'Later.')],
    'The nursing process starts with assessment.'),
  Q(SG, 'Family assessment', 'When conducting a family assessment, which action is most appropriate?',
    [o('Use a checklist format, completing the tool in the family\'s presence', true, 'Transparency, accuracy, engagement.'), o('Use quantitative data only to preserve objectivity', false, 'No.'), o('Interview one member to avoid repeated information', false, 'No.'), o('Make several visits accumulating data from all members', false, 'Not the marked answer.')],
    'Complete the tool with the family present.'),
  Q(SG, 'Family nursing', 'Characteristics of a healthy family include all of the following EXCEPT:',
    [o('Avoiding discussion of problems to avoid conflict', true, 'This is the exception: healthy families communicate openly.'), o('Making attempts to cope with problems', false, 'Healthy.'), o('Enhancement of individual development', false, 'Healthy.'), o('Respect for individual privacy and a sense of trust', false, 'Healthy.')],
    'Healthy families face problems directly. Avoiding them is dysfunction.'),
  Q(SG, 'Vulnerable populations', 'What is the best definition of vulnerable populations?',
    [o('Those at increased risk for adverse health outcomes', true, 'The broadest, most accurate definition.'), o('Individuals with chronic illnesses and high mortality', false, 'Too narrow.'), o('Those who share stressful social disorganization as a norm', false, 'Too narrow.'), o('Individuals who experience differences in outcomes compared with other groups', false, 'That describes disparities.')],
    'Vulnerability = increased risk of adverse health outcomes.'),
  Q(SG, 'Vulnerable populations', 'A community health nurse will be working with individuals experiencing homelessness. Which is essential to do first?',
    [o('Develop trust and establish rapport with the population', true, 'Foundation for everything else.'), o('Focus on the issue of homelessness', false, 'Not first.'), o('Visit the local shelter', false, 'A step, not the essential one.'), o('Help them seek shelter', false, 'After trust.')],
    'Trust first with vulnerable or marginalized groups.'),
  Q(SG, 'Vulnerable populations', 'Which client behavior best indicates the nurse is achieving empowerment with a vulnerable population?',
    [o('The clients take an active role in managing their health', true, 'Active engagement and self-management.'), o('The clients express feelings of hopelessness', false, 'Opposite.'), o('The clients now feel most situations are changeable', false, 'Attitude, not action.'), o('The clients state they may use available resources', false, 'Passive.')],
    'Empowerment shows up as action.'),
  Q(SG, 'Vulnerable populations', 'The public health nurse recognizes that vulnerable populations are at risk for:',
    [o('Increased morbidity and mortality', true, 'The defining characteristic.'), o('Domestic violence', false, 'Too narrow.'), o('Medical errors', false, 'Too narrow.'), o('Unintentional injury', false, 'Too narrow.')],
    'Consistent with the definition: increased risk for adverse outcomes.'),
  Q(SG, 'Vulnerable populations', 'Health disparities could result from all of the following EXCEPT:',
    [o('The individual care provider', true, 'The exception: disparities are driven by systemic factors.'), o('Access to care', false, 'A driver.'), o('Quality of care', false, 'A driver.'), o('Types of care', false, 'A driver.')],
    'Access, quality and types of care are the structural drivers of disparities.'),
  Q(SG, 'Vulnerable populations', 'Which vulnerable populations have been subjected to perceived poor quality of care and access to care? Select the 4 that apply (per the study guide key).',
    [o('HIV-infected persons', true, 'Stigmatized chronic condition.'), o('A 56-year-old man with hypertension', true, 'Chronic illness.'), o('A 42-year-old Hispanic single, unemployed mother', true, 'Socioeconomic and single-parent status.'), o('The homeless population', true, 'Homelessness.'), o('People in rural communities', false, 'Not marked correct in the study guide\'s key.')],
    'The study guide\'s key marks four groups; rural communities was not among them in that set.', { multi: true })
);

/* ---------- Cards ---------- */
[
  ['Prevention', 'Three levels of prevention', 'PRIMARY = prevent it (vaccines, teaching a healthy family). SECONDARY = find it early (screenings, self-exams). TERTIARY = live with it (rehab, support groups, complication prevention).', 'Guaranteed on the exam: scenario → level. Ask "does the person already have the condition?" No → primary. Found early → secondary. Yes → tertiary.'],
  ['Prevention', 'Where nurses concentrate', 'Primary prevention: keep people from getting sick in the first place. You still do the other two.', ''],
  ['Ch. 1', 'Population vs aggregate vs community', 'POPULATION: people in a place who may share traits but do not interact (a city\'s residents). AGGREGATE: people viewed as one unit, loosely connected (festival crowd). COMMUNITY: people who interact and share interests, with a sense of unity.', ''],
  ['Ch. 1', 'Three types of community', '"Place, passion, problem." Geographic (place) · Common interest (passion: book club, fans, associations) · Community of solution (problem: climate group, health task force).', ''],
  ['Ch. 2', 'Core public health functions', '"APA": Assessment (gather and analyze) → Policy development (make the plan) → Assurance (make sure services reach people).', ''],
  ['Ch. 2', 'Seven nurse roles', '"CEAM-CLR": Clinician, Educator, Advocate, Manager, Collaborator, Leader, Researcher.', 'Advocate = gets people resources (insurance). Collaborator = partners with organizations.'],
  ['Ch. 2', 'Seven practice settings', 'Home · Schools · Ambulatory (clinics) · Occupational (workplaces) · Residential institutions (nursing homes) · Faith communities · Community-at-large.', ''],
  ['Ch. 5', 'Five traits of every culture', '"LIST-D": Learned, Integrated, Shared, Tacit (mostly unspoken), Dynamic.', 'Ethnocentrism = "mine is better," which breaks communication and trust.'],
  ['Ch. 12', 'Planning process', 'Assess → Analyze & design → Plan & implement → Evaluate. Formative = during (fix it as you go). Summative = after (did it work?).', ''],
  ['Ch. 12', 'SMART objectives', 'Specific, Measurable, Achievable, Relevant, Timely. Goal = broad direction. Objective = the measurable step with a deadline.', '"By Feb 26, attendees will identify three healthy alternatives to fast food."'],
  ['Ch. 12', 'Why people change (or don\'t)', '"PRE": Predisposing (inside: beliefs, attitudes) · Reinforcing (people: family, peers, norms) · Enabling (world: access, resources, policies).', ''],
  ['Ch. 15', 'Community as client: three dimensions', 'STATUS (how healthy: morbidity, mortality, mental health, crime) · STRUCTURE (what exists: hospitals, clinics, schools) · PROCESS (how people relate).', ''],
  ['Ch. 15', 'Five types of community assessment', 'Windshield survey (drive and look) · Problem-oriented (one problem) · Subsystem (one sector) · Comprehensive (everything) · Assets (strengths).', 'Primary data = you collected it. Secondary = already existed.'],
  ['Ch. 7', 'Epidemiologic triangle', 'AGENT (the cause) · HOST (who gets it) · ENVIRONMENT (what lets it spread). Vectors carry the agent between hosts.', 'Malaria: Plasmodium · humans · warm humid climate.'],
  ['Ch. 7', 'Chain of transmission', '"A Real Exit Means Entry Happens": Agent → Reservoir → portal of Exit → Means of transmission → portal of Entry → susceptible Host.', 'Break one link, stop the spread.'],
  ['Ch. 7', 'Modes of transmission', 'Direct = touch or close droplet. Indirect = an object (vehicle: doorknob, fur, syringe). Airborne = tiny particles inhaled. Vector = a living carrier (mosquito).', ''],
  ['Ch. 7', 'Four kinds of immunity', 'Passive = borrowed, short (placenta, breast milk, immune globulin). Active = made by you, long (infection or vaccine). Cross = one protects against a cousin (cowpox/smallpox). Herd = enough people immune to protect the rest.', ''],
  ['Ch. 7', 'Natural history of disease', 'Susceptible (before exposure: primary) → Subclinical (exposed, no symptoms: secondary; labs can first detect here) → Clinical (symptoms: tertiary) → Recovery, disability or death.', ''],
  ['Ch. 7', 'Disease patterns', 'Endemic = always there at baseline. Epidemic = above baseline. Pandemic = across countries or continents.', ''],
  ['Rates', 'Rate formulas', 'Incidence = NEW cases ÷ population × 10ⁿ. Prevalence = EXISTING cases ÷ population × 10ⁿ (subtract the dead!). Crude mortality = all deaths ÷ population. Cause-specific = deaths from X ÷ population. Case fatality = deaths from X ÷ people WITH X × 100 (%). IMR = infant deaths ÷ LIVE BIRTHS × 1,000. Birth rate = live births ÷ population × 1,000. Attack rate = sick ÷ exposed × 100 (%).', 'Two traps: IMR uses live births; case fatality and attack rate are percentages.'],
  ['Rates', 'Denominator rule', 'Use the population at risk. Cervical cancer rate → women only. Attack rate → only the people exposed. Case fatality → only the people with the disease.', ''],
  ['Ch. 7', 'Study designs', 'Prevalence study = how common now. Case-control = start with the sick, look back for the exposure. Cohort = start with exposure, follow forward. Experimental = you assign the intervention (trial).', ''],
  ['Family', 'Family approaches', 'Family as context (backdrop to the individual) · Family as client (the unit is the patient) · Family as system (each member affects the others) · Family as component of society.', 'Interview everyone about the client\'s recovery = system.'],
  ['Family', 'Empowerment', '"Strengths, not deficits. With them, not for them." Success looks like clients taking an active role in their own health.', ''],
  ['Family', 'First step, always', 'Anxious new parents? Assess what they already know before teaching or referring.', 'Assess → then teach.'],
  ['Vulnerable', 'Vulnerable populations', 'Definition: at increased risk for adverse health outcomes. Working with them: build trust and rapport FIRST. Disparities come from access, quality and types of care (not the individual provider).', '']
].forEach(([cat, front, back, tip]) => window.RHYMES.push({ course: C, cat, front, back, tip, source: cat === 'Family' || cat === 'Vulnerable' ? SG : OBJ }));
})();
