/* Exam 1 Study Guide pack — practice questions and cards for every heading in the NURS 4620/4720 Exam 1
   study guide (75 questions incl. 2 NGN respiratory case studies). Answers come from the course decks and
   packets; where the guide lists a topic the materials only touch, standard nursing references fill the gap.
   Every item is tagged source: SG so the Focus setting can isolate study-guide practice. */
(function () {
const SG = 'NURS 4620/4720 Exam 1 Study Guide';
const Q = (topic, q, options, rationale, multi) => ({ source: SG, topic, q, options, rationale, multi: !!multi });
const o = (t, ok, why) => ({ t, ok, why });

window.QUICKFIRE.push(
  /* ---- Week 1: trauma / hypovolemic shock ---- */
  Q('Trauma with hypovolemic shock', 'A client with a femur fracture after a crash has HR 124, BP 88/54, pale cool skin, and says "I feel weak and dizzy." Which manifestations point to hypovolemic shock? Select all that apply.',
    [o('Tachycardia', true, 'The first compensation for lost volume.'), o('Hypotension', true, 'Compensation is failing.'), o('Pale, cool skin', true, 'Blood is shunted away from the skin.'), o('Dizziness and weakness', true, 'Brain hypoperfusion.'), o('Warm, flushed skin', false, 'That is distributive (septic or neurogenic) shock.'), o('Bradycardia', false, 'Neurogenic shock, not hypovolemic.')],
    'Hypovolemic shock: fast heart, falling pressure, cold pale skin, low urine output, altered mentation. Warm skin or a slow heart means a different shock.', true),
  Q('Trauma with hypovolemic shock', 'Which nursing interventions are priorities for a trauma client in early hypovolemic shock? Select all that apply.',
    [o('Two large-bore IV sites', true, 'Volume needs big access.'), o('Isotonic crystalloid bolus as prescribed', true, 'Restore circulating volume.'), o('Type and crossmatch; prepare blood products', true, 'Replace what was lost.'), o('Hourly urine output', true, 'Best bedside perfusion gauge.'), o('Give IV morphine before fluids are running', false, 'Drops the pressure further.'), o('Encourage oral fluids', false, 'NPO for likely surgery; cannot fix shock.')],
    'Access, volume, blood, and measurement. Analgesia comes once fluids are running, with the blood pressure watched.', true),
  Q('Trauma with hypovolemic shock', 'The trauma client takes lisinopril for hypertension. What is the nursing implication?',
    [o('Her "normal" BP may be low for her, and the ACE inhibitor can blunt the body\'s compensation, so hypotension is more dangerous', true, 'A hypertensive client at 110/70 may already be hypoperfused.'), o('Lisinopril should be given on schedule to protect the kidneys during shock', false, 'It lowers pressure; hold and clarify.'), o('It has no effect on shock', false, 'It matters.'), o('It causes the tachycardia', false, 'Blood loss does.')],
    'Comorbidities change the baseline. A client with chronic hypertension needs a higher pressure to perfuse organs, and an ACE inhibitor limits vasoconstriction.'),
  Q('Trauma with hypovolemic shock', 'The trauma client also has type 2 diabetes on metformin and a glucose of 238. Which implications apply? Select all that apply.',
    [o('Expect stress hyperglycemia; monitor glucose and treat per orders', true, 'Trauma raises cortisol and catecholamines.'), o('Metformin is typically held around surgery and contrast; poor perfusion raises lactic acidosis risk', true, 'Clarify with the provider.'), o('Hyperglycemia impairs wound healing and raises infection risk', true, 'Relevant after surgery.'), o('Give a dextrose bolus to prevent hypoglycemia', false, 'Glucose is 238.'), o('Diabetes makes the femur fracture bleed less', false, 'No.')],
    'Comorbidities do not change the shock priorities, but they add monitoring: glucose, the metformin question, and later healing.', true),
  Q('Trauma with hypovolemic shock', 'Which finding after a femur fracture is a NEW emergency rather than a sign of improvement?',
    [o('Pedal pulse becomes absent', true, 'Compartment syndrome or vascular injury: report immediately.'), o('Capillary refill improves to 2 seconds', false, 'Improvement.'), o('Urine output rises to 40 mL/hr', false, 'Improvement.'), o('Heart rate falls from 128 to 94', false, 'Improvement.')],
    'Evaluate limb perfusion separately from whole-body perfusion. A pulse that disappears is a threat to the leg.'),
  /* ---- Week 1: meds in case study 2 ---- */
  Q('Meds in Case Study 2', 'Why is aspirin 81 mg prescribed after an ischemic stroke?',
    [o('Antiplatelet: prevents a new clot from forming', true, 'Secondary stroke prevention.'), o('Pain relief for the headache', false, 'Not the purpose.'), o('To thin the blood before thrombolysis', false, 'Never before the CT.'), o('To lower blood pressure', false, 'No.')],
    'Aspirin is given for secondary prevention after ischemic stroke, only after hemorrhage is excluded.'),
  Q('Meds in Case Study 2', 'Before giving metoprolol tartrate, the nurse must check:',
    [o('Heart rate and blood pressure; hold per parameters (commonly HR < 60)', true, 'Beta-blockers slow the heart and lower pressure.'), o('Blood glucose only', false, 'Beta-blockers can mask hypoglycemia, but the hold parameter is the rate.'), o('Potassium', false, 'Not the primary check.'), o('Nothing; it is a scheduled medication', false, 'Always check.')],
    'The stroke case had a heart rate of 54: hold and clarify. Beta-blockers can also mask the tachycardia of hypoglycemia in a diabetic client.'),
  Q('Meds in Case Study 2', 'Potassium chloride extended-release 20 mEq is ordered PO for a client who is NPO with an NG tube and a potassium of 3.2. The nurse should:',
    [o('Hold and clarify: request the liquid formulation for the tube; never crush extended-release', true, 'Crushing ER dumps the dose and can irritate the gut.'), o('Crush the tablet and flush it down the tube', false, 'Never crush ER.'), o('Skip the dose because the client is NPO', false, 'NPO does not cancel the need; the potassium is low.'), o('Give it IV push instead', false, 'Potassium is NEVER given IV push.')],
    'Potassium replaces the deficit (3.2). Route and formulation must be right: liquid via the tube, and potassium is never pushed IV.'),
  Q('Meds in Case Study 2', 'Why is pantoprazole prescribed, and how is it given through an NG tube?',
    [o('Reduces stomach acid (stress-ulcer and reflux protection); use the delayed-release oral suspension, never crushed granules', true, 'Crushing destroys the enteric coating.'), o('Prevents nausea; crush and mix into the feeding', false, 'Wrong purpose and wrong technique.'), o('Treats infection; give with the antibiotic', false, 'No.'), o('It cannot be given to a stroke client', false, 'It can, in the right form.')],
    'A proton-pump inhibitor for GI protection. Delayed-release forms need the suspension made for tubes.'),
  Q('Meds in Case Study 2', 'A stroke client on continuous tube feeding has insulin glargine 18 units daily and lispro per correction scale ordered. Glucose is 204. The nurse should:',
    [o('Give both subcutaneously as prescribed; NPO status does not stop subcutaneous insulin, and the client is being fed continuously', true, 'Glargine is basal; lispro corrects the 204.'), o('Hold all insulin because the client is NPO', false, 'He receives continuous nutrition and glucose is high.'), o('Give the insulin through the NG tube', false, 'Insulin is never given enterally.'), o('Give lispro only if the client eats a meal', false, 'Correction scale is based on the glucose reading.')],
    'Glargine = long-acting basal (no peak, never mixed). Lispro = rapid-acting, onset about 15 minutes, dosed to the reading. Monitor for hypoglycemia, which a stroke client with aphasia may not be able to report.'),
  Q('Meds in Case Study 2', 'Acetaminophen 650 mg every 6 hours PRN is ordered. Which nursing consideration applies?',
    [o('Track the total daily dose (generally no more than 3–4 g/day) and watch liver function', true, 'Hepatotoxic in overdose.'), o('Hold if the heart rate is below 60', false, 'That is metoprolol.'), o('Give only for temperature above 101 °F', false, 'PRN for pain or fever per order.'), o('It must be given on an empty stomach', false, 'No.')],
    'The main safety issue with acetaminophen is the 24-hour total, especially when other products contain it.'),
  Q('Nursing implications for a patient who had a stroke', 'Which nursing implications apply to a client with a recent ischemic stroke, right-sided weakness, expressive aphasia and dysphagia? Select all that apply.',
    [o('Aspiration precautions: head of bed up, NPO until cleared, tube feeding with HOB ≥ 30°', true, 'Dysphagia is the biggest immediate safety risk.'), o('Communicate with yes/no questions and give time; he understands speech', true, 'Expressive aphasia: comprehension intact.'), o('Fall precautions and approach from the unaffected side for care', true, 'Weakness and neglect risk.'), o('Frequent neuro checks to catch a new change from baseline', true, 'Recurrent stroke or hemorrhagic conversion.'), o('Speak loudly and slowly because he cannot understand', false, 'He understands; he cannot produce speech.'), o('Lay flat to improve cerebral blood flow', false, 'Aspiration risk; 30° is the standard.')],
    'Safety (swallow, falls), communication that respects intact comprehension, and constant reassessment.', true),
  /* ---- Prioritization ---- */
  Q('Prioritization', 'After report, which client should the nurse see first?',
    [o('Heart failure client: newly restless, RR 30, new crackles, SpO₂ dropped from 96% to 91%', true, 'Acute change; risk of respiratory failure.'), o('COPD client: SpO₂ 89% on 2 L, same as the last three shifts', false, 'Abnormal but expected and unchanged.'), o('Post-op day 2: pain 6/10, scheduled analgesic due', false, 'Stable.'), o('Diabetic client who needs discharge teaching tomorrow', false, 'Teaching waits.')],
    'The change from baseline is the clue. The lowest number is not always the priority.'),
  Q('Prioritization', 'Which nursing intervention should be implemented first for a post-op client who is pale, restless, HR 118, BP 96/58, with new bright-red drainage on the dressing?',
    [o('Focused assessment for bleeding and notify the provider', true, 'Assess the source, escalate with the trend.'), o('Give the scheduled pain medication', false, 'Would lower BP.'), o('Document and recheck in an hour', false, 'Too slow.'), o('Apply a warm blanket', false, 'Comfort, not survival.')],
    'Assess before you act, then act on circulation. Report the trend, not just the number.'),
  Q('Prioritization', 'Orders for a septic post-op client with BP 82/46 and two patent IVs: crystalloid bolus, IV antibiotic, blood cultures, urinary catheter, acetaminophen. Which order should the nurse implement first?',
    [o('Begin the IV crystalloid bolus', true, 'Circulation is critical now.'), o('Insert the urinary catheter', false, 'Monitoring comes after resuscitation starts.'), o('Give acetaminophen', false, 'Comfort.'), o('Draw cultures and wait for results before anything else', false, 'Cultures first when possible, but never delay fluids in shock.')],
    'When several orders are correct, the one that fixes what kills first goes first: volume for a pressure of 82/46, then cultures and antibiotics within the hour.'),
  Q('Prioritization', 'Four clients received an intervention. Who needs the EARLIEST reassessment?',
    [o('Client who received IV furosemide for acute dyspnea and crackles', true, 'Given for instability; must evaluate the response.'), o('Client who received acetaminophen for a temperature of 100.9 °F', false, 'Low risk.'), o('Client who received a stool softener', false, 'Low risk.'), o('Client who received a multivitamin with breakfast', false, 'Routine.')],
    'Priority includes reassessment after a high-risk or acute intervention. Reassessment closes the loop.'),
  /* ---- Neuro assessment ---- */
  Q('Focused neurological assessment', 'Which finding is the EARLIEST and most sensitive sign of rising intracranial pressure?',
    [o('A change in level of consciousness', true, 'Restless, drowsy, confused comes before pupils or vital signs.'), o('Unequal pupils', false, 'Later.'), o('Bradycardia with widening pulse pressure', false, 'Late: Cushing\'s.'), o('Irregular respirations', false, 'Late.')],
    'LOC first, pupils next, Cushing\'s triad last. Do not wait for the triad.'),
  Q('Focused neurological assessment', 'A client\'s GCS goes from 14 to 11 over 30 minutes with a new sluggish 5 mm pupil. The nurse should:',
    [o('Escalate immediately (neuro/rapid response); a 2-point drop is an emergency', true, 'Trend, not score.'), o('Recheck in an hour', false, 'Herniation can happen in minutes.'), o('Give the PRN opioid for headache', false, 'Masks the exam and depresses breathing.'), o('Document as expected after head injury', false, 'Never.')],
    'A score is only useful when you interpret the change. Chart the trend and escalate on the trend.'),
  Q('Focused neurological assessment', 'During the pronator drift test, the client\'s right arm slowly drifts downward with eyes closed. This indicates:',
    [o('Subtle weakness on the right, a focal motor finding', true, 'Early sign of a stroke or lesion on the opposite hemisphere.'), o('Normal fatigue', false, 'Drift is never normal.'), o('A global process such as rising ICP', false, 'One-sided = focal.'), o('A sensory problem only', false, 'It is motor.')],
    'Focal change (one side, one function) points to a vessel territory. Global deterioration (LOC, pupils, vomiting, breathing) points to pressure.'),
  Q('Focused neurological assessment', 'Which changes are never casual and require escalation? Select all that apply.',
    [o('New facial asymmetry or unilateral weakness', true, 'Focal red flag.'), o('New aphasia or dysarthria', true, 'Focal red flag.'), o('Declining level of consciousness', true, 'Global red flag.'), o('Unequal or non-reactive pupils', true, 'Global red flag.'), o('Repeated vomiting or a new seizure', true, 'Global red flag.'), o('A headache 3/10 that responds to acetaminophen', false, 'Monitor; not a red flag by itself.')],
    'Focal change or global deterioration: both mean stop and escalate.', true),
  /* ---- ICP ---- */
  Q('Increased intracranial pressure', 'Which vital-sign pattern is Cushing\'s triad?',
    [o('Rising systolic BP with widening pulse pressure, bradycardia, irregular respirations', true, 'Pressure HIGH, pulse LOW, breathing WEIRD.'), o('Hypotension, tachycardia, tachypnea', false, 'Shock.'), o('Hypotension, bradycardia, warm skin', false, 'Neurogenic shock.'), o('Fever, tachycardia, hypotension', false, 'Sepsis.')],
    'Cushing\'s triad is a late sign of rising ICP and impending herniation.'),
  Q('Increased intracranial pressure', 'Which nursing actions help lower or avoid raising ICP? Select all that apply.',
    [o('Head of bed 30° with head and neck midline', true, 'Promotes venous drainage.'), o('Limit suctioning to brief passes (about 10–15 seconds) and only when needed', true, 'Suctioning spikes ICP.'), o('Prevent hypoxia and hypercapnia', true, 'Both dilate cerebral vessels.'), o('Keep the environment calm; cluster care to allow rest', true, 'Stimulation raises ICP.'), o('Place flat with hips flexed', false, 'Blocks venous return from the head.'), o('Give a rapid IV fluid bolus', false, 'Sudden volume can raise ICP.')],
    'Drain, oxygenate, calm. Avoid anything that raises pressure in the chest, abdomen or neck.', true),
  Q('Increased intracranial pressure', 'A client with rising ICP receives IV mannitol. The nurse evaluates the response by monitoring:',
    [o('Neuro exam (LOC, pupils, motor), urine output, serum osmolality and electrolytes', true, 'Osmotic diuretic: pulls water out of the brain and out through the kidneys.'), o('Blood glucose every hour', false, 'Not the effect.'), o('Bowel sounds', false, 'No.'), o('Peak flow', false, 'No.')],
    'Mannitol (or hypertonic saline) draws water out of brain tissue. Effective = neuro exam improves; watch for dehydration, low pressure and electrolyte shifts.'),
  Q('Increased intracranial pressure', 'After head trauma, which observation is FALSE reassurance rather than improvement?',
    [o('The client becomes quieter and stops complaining of headache, without a reassessment', true, 'Quiet can be a falling LOC.'), o('GCS trends back toward baseline', false, 'Real improvement.'), o('Pupils become equal and reactive', false, 'Real improvement.'), o('Motor response improves', false, 'Real improvement.')],
    'In the brain, "calmer" can be "worse." Trust the neuro exam trend, not a quiet room.'),
  /* ---- Stroke ---- */
  Q('Stroke', 'Sudden right facial droop, right arm drift and expressive aphasia in a client with atrial fibrillation. What must happen FIRST in the first five minutes? Select all that apply.',
    [o('Activate the stroke response team', true, 'Starts the pathway.'), o('Check point-of-care glucose', true, 'Hypoglycemia mimics stroke.'), o('Keep NPO and prepare for urgent non-contrast head CT', true, 'Bleed versus clot decides everything.'), o('Note the last-known-well time', true, 'The treatment clock runs from it.'), o('Give aspirin before imaging', false, 'Unsafe until hemorrhage is excluded.'), o('Lower systolic BP below 120', false, 'Starves the brain.')],
    'Sugar, then scan, then the plan. Nothing antithrombotic before the CT.', true),
  Q('Stroke', 'How does the nurse distinguish ischemic from hemorrhagic stroke at the bedside?',
    [o('You cannot reliably; the non-contrast CT decides, so no antithrombotic is given until it is read', true, 'Symptoms overlap.'), o('Hemorrhagic stroke never causes weakness', false, 'It does.'), o('Ischemic stroke always causes a severe headache', false, 'Sudden severe headache and vomiting suggest bleeding, but imaging decides.'), o('A-fib means it must be hemorrhagic', false, 'A-fib is a clot source: ischemic.')],
    'Treat the presentation as stroke, keep the clock, and let the CT separate clot from bleed.'),
  Q('Stroke', 'Before IV alteplase (thrombolytic), blood pressure generally must be:',
    [o('Below 185/110', true, 'Higher pressures raise bleeding risk.'), o('Below 120/80', false, 'Over-lowering reduces cerebral perfusion.'), o('Above 200 systolic', false, 'No.'), o('Blood pressure does not matter', false, 'It matters.')],
    'Thrombolysis threshold is 185/110. Lowering systolic below 120 could reduce cerebral perfusion.'),
  Q('Stroke', 'During the alteplase infusion the client develops a sudden severe headache, vomiting, and becomes difficult to arouse. First action?',
    [o('Stop the infusion, then escalate, stabilize airway and breathing, and prepare for emergent CT', true, 'Acute decline during thrombolysis is hemorrhage until excluded.'), o('Slow the infusion and reassess in 15 minutes', false, 'Stop it.'), o('Give aspirin', false, 'Worsens bleeding.'), o('Lay flat and dim the lights', false, 'Airway and escalation first.')],
    'Stop. Escalate. Stabilize. Confirm. Then reassess LOC, pupils, motor, airway and BP continuously.'),
  Q('Stroke', 'Which discharge approach best confirms a stroke client (limited health literacy, preferred language Vietnamese) understands warning signs?',
    [o('Teach-back through a qualified interpreter: "Show me how you will explain the warning signs and what you will do"', true, 'Education is not complete because a box was clicked.'), o('Ask "Do you understand?" and document yes', false, 'Not evidence.'), o('Have the daughter translate the discharge papers', false, 'Family are not qualified interpreters for medical teaching.'), o('Give the printed handout in English', false, 'No.')],
    'Discharge is a clinical judgment decision: language support, teach-back, and a plan for follow-up and barriers.'),
  /* ---- Seizures ---- */
  Q('Seizures', 'During a generalized tonic-clonic seizure, the nurse should: Select all that apply.',
    [o('Turn the client to the side and protect the head', true, 'Airway and injury prevention.'), o('Note the time it started and what the movements look like', true, 'Duration drives treatment.'), o('Loosen clothing at the neck; move objects away', true, 'Safety.'), o('Put an oral airway or padded tongue blade between the teeth', false, 'Never force anything into the mouth.'), o('Restrain the limbs to stop the movements', false, 'Causes injury.')],
    'Protect, time, observe. Nothing in the mouth, no restraints.', true),
  Q('Seizures', 'Which post-ictal finding is UNEXPECTED and requires immediate action?',
    [o('RR 8 with SpO₂ 88% after IV lorazepam', true, 'Respiratory depression: airway first.'), o('Drowsy but arousable for 30–60 minutes', false, 'Expected.'), o('Confusion and headache on waking', false, 'Expected.'), o('Sore muscles and a bitten tongue', false, 'Expected.')],
    'Know the expected abnormal (post-ictal sleepiness) so the unexpected (hypoventilation, unresponsiveness, another seizure) stands out.'),
  Q('Seizures', 'Status epilepticus is:',
    [o('A seizure lasting 5 minutes or more, or repeated seizures without recovery between them; a medical emergency treated first with a benzodiazepine', true, 'Brain damage and death risk rise with duration.'), o('Any seizure in a client with epilepsy', false, 'No.'), o('A seizure that stops on its own within 2 minutes', false, 'Typical seizure.'), o('The sleepy period after a seizure', false, 'That is post-ictal.')],
    'Time it. At five minutes it is status: airway, oxygen, IV benzodiazepine, then a loading anti-seizure drug, and watch the breathing after the benzo.'),
  /* ---- SCI ---- */
  Q('Brain and spinal cord injury', 'Which set of findings is neurogenic shock rather than spinal shock?',
    [o('Hypotension, bradycardia, warm dry skin after a T4 injury', true, 'Hemodynamic: lost sympathetic tone.'), o('Flaccid paralysis, absent reflexes, loss of bladder tone', false, 'Spinal shock: neurologic.'), o('Tachycardia, cold clammy skin, low BP', false, 'Hypovolemic shock.'), o('Fever, tachycardia, warm flushed skin', false, 'Septic shock.')],
    'Spinal shock: the nerves go flat. Neurogenic shock: the pressure goes flat (T6 or above). They can coexist.'),
  Q('Brain and spinal cord injury', 'How does the nurse know spinal shock is resolving?',
    [o('Reflex activity returns below the level of injury', true, 'Return of reflexes marks resolution.'), o('Blood pressure stabilizes', false, 'That is neurogenic shock resolving.'), o('The client can walk', false, 'Not the marker.'), o('Skin becomes cool', false, 'No.')],
    'Different problems resolve on different timelines: reflexes for spinal shock, circulation for neurogenic shock.'),
  Q('Brain and spinal cord injury', 'In acute cervical spinal cord injury, which change should make the nurse stop a transfer and escalate?',
    [o('New difficulty breathing or falling SpO₂', true, 'Ascending edema can paralyze the diaphragm.'), o('Reflexes remain absent', false, 'Expected in spinal shock.'), o('Skin remains warm and dry', false, 'Expected in neurogenic shock.'), o('The client asks for water', false, 'Not a threat.')],
    'In SCI, prevent the second injury: alignment, and above all airway and breathing.'),
  Q('Autonomic dysreflexia', 'A client with a chronic T4 injury has a pounding headache, flushing and sweating above the injury, BP 202/108, and a kinked urinary catheter. Order the response.',
    [o('Sit upright → loosen restrictive clothing → restore bladder drainage → recheck BP frequently', true, 'SIT, LOOSEN, DRAIN, RECHECK.'), o('Lay flat → give antihypertensive → call provider', false, 'Flat raises cerebral pressure; remove the trigger first.'), o('Give IV fluids → sit up → catheterize', false, 'Fluids raise pressure.'), o('Recheck BP in 30 minutes', false, 'Stroke-level pressure.')],
    'Trigger → reflex → hypertension. Bladder first, then bowel, then skin. Medication only if pressure stays high after the trigger is removed.'),
  Q('Autonomic dysreflexia', 'Why is the skin flushed and sweaty ABOVE the injury but pale and cool BELOW it in autonomic dysreflexia?',
    [o('Massive sympathetic vasoconstriction below the lesion raises BP; the brain answers with parasympathetic vasodilation above, but the signal cannot pass the injury', true, 'Sympathetic below, parasympathetic above.'), o('Infection below the injury', false, 'No.'), o('The catheter is leaking', false, 'No.'), o('Hypothermia', false, 'No.')],
    'Sympathetic and parasympathetic responses are separated by the injury: the reflex fires below; the brake works only above.'),
  /* ---- Neuro meds ---- */
  Q('Neurological medications and treatments', 'A client received IV lorazepam for a seizure. What is the priority monitoring afterward?',
    [o('Respiratory rate, SpO₂ and level of consciousness: benzodiazepines depress breathing', true, 'After the benzo, the breathing is the danger.'), o('Urine output', false, 'Not the priority.'), o('Blood glucose', false, 'Check once; not the drug effect.'), o('Reflexes', false, 'No.')],
    'Evaluate the response to the treatment AND the risk the treatment created.'),
  Q('Neurological medications and treatments', 'Nursing considerations for IV alteplase in ischemic stroke include: Select all that apply.',
    [o('Confirm no hemorrhage on CT and BP below 185/110 before starting', true, 'Eligibility.'), o('Bleeding precautions: no IM injections, minimal venipuncture, no antithrombotics for 24 hours', true, 'Thrombolytic.'), o('Frequent neuro checks and BP during and after the infusion', true, 'Detect hemorrhagic conversion.'), o('Stop the infusion for any acute neuro decline or severe headache', true, 'Bleed until excluded.'), o('Give aspirin at the same time', false, 'Not within 24 hours.')],
    'A thrombolytic dissolves clots everywhere. Eligibility, bleeding precautions, reassessment.', true),
  Q('Neurological medications and treatments', 'For a client in neurogenic shock, the nurse anticipates:',
    [o('IV fluids, a vasopressor to restore vascular tone, and atropine available for symptomatic bradycardia', true, 'Treat lost sympathetic tone.'), o('Diuretics to reduce edema', false, 'Wrong direction.'), o('Beta-blockers to control heart rate', false, 'The rate is already slow.'), o('Warm blankets as the main treatment', false, 'Monitor temperature, but blankets do not fix the pressure.')],
    'Neurogenic shock = loss of sympathetic tone: give tone back (pressor) and volume, block the vagus (atropine) if the heart is too slow.'),
  /* ---- Respiratory ---- */
  Q('Respiratory assessment and deterioration', 'Which findings in an asthma client indicate respiratory status is DECLINING? Select all that apply.',
    [o('Retraction of sternal muscles', true, 'Accessory muscle use.'), o('Tachycardia', true, 'Compensation.'), o('Wheezing that becomes quiet with single-word speech', true, 'Silent chest: air is not moving.'), o('SaO₂ 95%', false, 'Acceptable.'), o('Pink mucous membranes', false, 'Normal.')],
    'From the course review question: wheezing, retractions and tachycardia signal decline. A quiet chest after loud wheezing is worse, not better.', true),
  Q('Acid-base', 'ABG: pH 7.31, PaCO₂ 51, HCO₃⁻ 28. Interpretation?',
    [o('Partially compensated respiratory acidosis', true, 'pH low, CO₂ high (opposite = respiratory), bicarbonate rising to compensate.'), o('Metabolic acidosis', false, 'HCO₃⁻ would be low.'), o('Respiratory alkalosis', false, 'pH would be high.'), o('Fully compensated', false, 'pH is still abnormal.')],
    'ROME: Respiratory = Opposite. This is the COPD client\'s chronic pattern; the kidneys hold onto bicarbonate.'),
  Q('Acid-base', 'ABG: pH 7.47, PaCO₂ 34, HCO₃⁻ 22, PaO₂ 80 in a client with pneumonia breathing 32 times a minute. Interpretation and nursing focus?',
    [o('Uncompensated respiratory alkalosis from hyperventilation; treat the cause of the fast breathing (hypoxia, pain, anxiety) and oxygenate', true, 'Blowing off CO₂.'), o('Metabolic alkalosis; give fluids', false, 'HCO₃⁻ is normal.'), o('Respiratory acidosis; prepare to intubate', false, 'CO₂ is low.'), o('Normal', false, 'pH is high.')],
    'Early in pneumonia, ARDS or PE the client hyperventilates: respiratory alkalosis. When the client tires, CO₂ climbs and it flips to acidosis.'),
  Q('Acid-base', 'ABG: pH 7.15, HCO₃⁻ 12, PaCO₂ 30 in a client with glucose 520 and deep rapid breathing. Interpretation?',
    [o('Partially compensated metabolic acidosis (DKA); the Kussmaul breathing is the lungs compensating', true, 'Metabolic = Equal: pH and HCO₃⁻ both low.'), o('Respiratory acidosis', false, 'CO₂ is low.'), o('Metabolic alkalosis', false, 'pH is low.'), o('Respiratory alkalosis as the primary problem', false, 'The low CO₂ is compensation.')],
    'Treat the cause (fluids, insulin); the breathing normalizes as the acidosis clears. Endpoint is the pH, not the glucose.'),
  Q('Pneumonia', 'Which nursing interventions are priorities for a client with pneumonia and impaired gas exchange? Select all that apply.',
    [o('Elevate the head of the bed 30–45°', true, 'Chest expansion.'), o('Supplemental oxygen as ordered', true, 'Oxygenation.'), o('Increase fluids (unless contraindicated) to thin secretions', true, 'Mobilize secretions.'), o('Turn, cough, deep breathe; incentive spirometer', true, '"If it sits, it either clots or cultures."'), o('Give a cough suppressant around the clock', false, 'Suppressing a productive cough traps secretions.'), o('Restrict oral intake', false, 'Fluids thin secretions.')],
    'Improve oxygenation and decrease work of breathing; keep secretions moving.', true),
  Q('Pneumonia', 'Which order sequence is correct for a newly admitted pneumonia client with SpO₂ 90%?',
    [o('Oxygen → sputum culture → IV antibiotic → teach yearly flu vaccine', true, 'Breathing, then culture before the drug, then treat, then teach.'), o('Antibiotic → oxygen → culture → teach', false, 'Culture before antibiotics when possible.'), o('Teach → culture → oxygen → antibiotic', false, 'Teaching last.'), o('Culture → teach → antibiotic → oxygen', false, 'Oxygen first.')],
    'The course review answer: C, B, A, D. Oxygen first, cultures before antibiotics, teaching last.'),
  Q('Pneumonia', 'Which clients are at increased risk for pneumonia? Select all that apply.',
    [o('Client with dysphagia', true, 'Aspiration.'), o('Client with AIDS', true, 'Immunosuppression.'), o('Client on mechanical ventilation after a head injury', true, 'Ventilator-associated pneumonia.'), o('Client with myasthenia gravis', true, 'Weak respiratory muscles, poor airway clearance.'), o('Client vaccinated for pneumococcus and influenza 6 months ago', false, 'Protected.'), o('Post-op client who had local anesthesia', false, 'Not general anesthesia; low risk.')],
    'Course review question: A, B, E, F. Think aspiration, immune status, ventilation, and airway clearance.', true),
  Q('Pneumonia', 'An 84-year-old with pneumonia has BP 88/54, HR 118, lactate 4.5, confusion and urine output 15 mL/hr. Which orders does the nurse expect? Select all that apply.',
    [o('Blood cultures', true, 'Before antibiotics when possible.'), o('Broad-spectrum IV antibiotics', true, 'Within the hour.'), o('Supplemental oxygen', true, 'SpO₂ 90%.'), o('30 mL/kg IV crystalloid', true, 'Fill dilated vessels.'), o('Vasopressor if hypotension persists', true, 'Restore tone.'), o('Indwelling urinary catheter', true, 'Hourly output guides resuscitation.'), o('Fluid restriction because of his age', false, 'Shock needs volume; monitor lungs.')],
    'Septic shock: hypotension + lactate ≥ 4. The bundle: cultures, antibiotics, oxygen, fluids, pressors, catheter.', true),
  Q('ARDS', 'The hallmark of ARDS is:',
    [o('Refractory hypoxemia: oxygen alone does not fix it', true, 'Diffuse alveolar damage.'), o('Wheezing that responds to albuterol', false, 'Asthma.'), o('Purulent sputum with fever', false, 'Pneumonia.'), o('Pleuritic chest pain with hemoptysis', false, 'PE.')],
    'ARDS: sudden dyspnea, crackles, worsening SpO₂ despite increasing oxygen; early respiratory alkalosis, late acidosis; treated with ventilation, prone positioning, and treating the cause.'),
  Q('ARDS', 'Which complication should the nurse anticipate in a client with ARDS?',
    [o('Multiple organ dysfunction syndrome (MODS)', true, 'Hypoxia and inflammation injure every organ.'), o('Hyperthyroidism', false, 'No.'), o('Appendicitis', false, 'No.'), o('Cataracts', false, 'No.')],
    'Course review answer: MODS. Also watch for infection, DVT, and pressure injuries.'),
  Q('Pulmonary embolism', 'A post-op client suddenly has pleuritic chest pain, RR 30, anxiety, hemoptysis, SpO₂ 88%, and a swollen tender calf. The nurse anticipates: Select all that apply.',
    [o('Oxygen and high-Fowler\'s position', true, 'Oxygenate.'), o('IV access and anticoagulation (heparin) as ordered', true, 'Stop clot extension.'), o('CT pulmonary angiography', true, 'Preferred diagnostic test.'), o('Cardiac monitoring and frequent vital signs', true, 'Watch for shock.'), o('Massage the calf', false, 'Could dislodge more clot.'), o('Ambulate to prevent more clots', false, 'Bed rest in the acute phase.')],
    'PE: sudden dyspnea, pleuritic pain, hemoptysis, sense of doom, tachycardia, DVT source. D-dimer elevated, ABG respiratory alkalosis with hypoxemia.', true),
  Q('Pulmonary embolism', 'A client on IV heparin for PE has gums oozing when brushing. The nurse should:',
    [o('Report it and check the aPTT; bleeding is the main risk of anticoagulation', true, 'Evaluate the treatment\'s risk.'), o('Ignore it; minor bleeding is expected', false, 'Report.'), o('Stop the heparin without an order', false, 'Report first.'), o('Give aspirin for the discomfort', false, 'Adds bleeding risk.')],
    'Evaluate outcomes on both sides: the PE improving AND the side effects of what you gave.'),
  Q('TB', 'A client starting RIPE therapy for tuberculosis asks about side effects. Which teaching is correct? Select all that apply.',
    [o('Rifampin turns urine, sweat and tears red-orange', true, 'Harmless but alarming.'), o('Isoniazid can cause peripheral neuropathy; vitamin B6 helps prevent it', true, 'Course slide.'), o('Ethambutol can affect vision and red-green color perception; report changes', true, 'Eye exams.'), o('All four drugs can affect the liver; report dark urine, jaundice, nausea', true, 'Hepatotoxicity.'), o('Stop the medications once the cough is gone', false, 'Months of therapy; direct observation therapy ensures completion.')],
    'RIPE: Rifampin, Isoniazid, Pyrazinamide (gout-like joint pain), Ethambutol. Airborne precautions; DOT.', true),
  Q('TB', 'A woman in her first trimester is diagnosed with active TB disease. The provider will:',
    [o('Begin anti-tuberculosis medications immediately', true, 'Untreated TB is more dangerous to the pregnancy than treatment.'), o('Wait until after delivery', false, 'No.'), o('Delay until amniocentesis results', false, 'No.'), o('Begin treatment at a reduced dose', false, 'Standard regimen.')],
    'Course review question: begin treatment immediately.'),
  Q('Asthma', 'A client 2 hours after admission has SaO₂ 91%, audible wheezes, and accessory muscle use. Which medication class should the nurse expect?',
    [o('Beta-2 agonist (albuterol)', true, 'Dilates bronchioles, relieves wheezing.'), o('Beta-blocker', false, 'Blocks beta-2: tightens airways.'), o('Antibiotic', false, 'No infection cue.'), o('Antiviral', false, 'No.')],
    'Course review answer: beta-2 agonist. Rescue first, then steroids for inflammation.'),
  Q('Asthma', 'Which medications should be avoided or questioned in a client with asthma? Select all that apply.',
    [o('Non-selective beta-blockers (e.g., labetalol, propranolol)', true, 'Block beta-2 receptors in the lungs.'), o('NSAIDs such as ibuprofen', true, 'Can induce bronchospasm.'), o('Aspirin', true, 'Can induce bronchospasm.'), o('Inhaled corticosteroids', false, 'Core controller therapy.'), o('Ipratropium', false, 'Anticholinergic bronchodilator; used with albuterol.')],
    'Labetalol and ibuprofen make the asthmatic\'s airway tighten.', true),
  Q('Asthma', 'After two nebulizer treatments and a steroid, an asthma client has extreme labored breathing, confusion, blue lips, HR 128, RR 38, SpO₂ 85%. The nurse recognizes:',
    [o('Status asthmaticus: give high-flow oxygen, epinephrine as ordered, and prepare for possible intubation', true, 'Not responding to standard treatment.'), o('Anaphylaxis to the nebulizer', false, 'No allergic cues.'), o('Improvement; the treatment is working', false, 'Clearly worse.'), o('Pulmonary edema; give a diuretic', false, 'No.')],
    'From the course bow-tie: status asthmaticus. Monitor SpO₂ and respirations: muscle fatigue leads to respiratory failure.'),
  Q('COPD', 'Discharge teaching for a COPD client with a new albuterol prescription. Which statement shows understanding?',
    [o('"I can have an increase in my heart rate while taking this medication."', true, 'Beta-2 agonists cause tachycardia and tremor.'), o('"This medication can increase my blood sugar."', false, 'That is a steroid.'), o('"This medication can decrease my immune response."', false, 'Steroid.'), o('"I can get mouth sores from it."', false, 'Inhaled steroids cause thrush; rinse the mouth.')],
    'Course review answer: increased heart rate.'),
  Q('COPD', 'Oxygen for a client with COPD should be titrated to keep SpO₂ at:',
    [o('88–92%', true, 'Too much oxygen blunts the hypoxic drive and CO₂ climbs.'), o('95–100%', false, 'Risk of CO₂ retention.'), o('80–85%', false, 'Too low.'), o('Whatever makes the client comfortable', false, 'No.')],
    '"88 to 92 is the O₂ for you." Lowest flow that holds the target.'),
  Q('COPD', 'Which interventions belong in the plan for a COPD exacerbation with pneumonia? Select all that apply.',
    [o('Pursed-lip breathing', true, 'Prolongs exhalation, releases trapped CO₂.'), o('Flutter valve or Acapella to mobilize secretions', true, 'Positive expiratory pressure.'), o('High-Fowler\'s or tripod positioning', true, 'Improves ventilation.'), o('IV glucocorticoid and antibiotic', true, 'Inflammation and infection.'), o('Cough suppressant', false, 'Secretions must come up.'), o('Fluid restriction', false, 'Fluids thin secretions.')],
    'From the COPD case: mobilize secretions, ease exhalation, treat inflammation and infection.', true),
  Q('COPD', 'A COPD client is prescribed theophylline. The nurse teaches:',
    [o('Blood levels must be monitored; the therapeutic range is narrow and toxicity causes nausea, tachycardia and seizures', true, 'Course slide: narrow therapeutic range.'), o('Take extra doses when short of breath', false, 'Toxicity.'), o('It is a rescue inhaler', false, 'Oral methylxanthine, not rescue.'), o('No monitoring is needed', false, 'Wrong.')],
    'Methylxanthines relax bronchial smooth muscle but need level monitoring; used only when other treatments fail.'),
  /* ---- Burns ---- */
  Q('Burn classification', 'Which description matches a full-thickness burn?',
    [o('Dry, leathery, may be white, brown or charred, with reduced or absent sensation in the deepest area', true, 'Epidermis and dermis destroyed; nerve endings gone.'), o('Red, dry, painful, blanches; not counted in TBSA', false, 'Superficial.'), o('Moist, blistered, very painful', false, 'Superficial partial-thickness.'), o('Only the epidermis is involved', false, 'Superficial.')],
    'Depth: superficial (epidermis, painful, not counted), partial-thickness (into dermis, blisters, painful), full-thickness (dry, leathery, less sensate).'),
  Q('Burn classification', 'A client with a large full-thickness burn says "it really doesn\'t hurt here." The nurse understands:',
    [o('Nerve endings are destroyed; absence of pain does NOT mean a less severe injury', true, 'Pain never grades burn severity.'), o('The burn is superficial', false, 'Opposite.'), o('The client is in denial', false, 'No.'), o('Analgesia is not needed', false, 'Surrounding partial-thickness areas hurt intensely; procedural pain is severe.')],
    'Do not judge severity from pain alone. Burn pain is background, breakthrough and procedural; manage it multimodally and reassess.'),
  Q('Burn severity', 'Which factors increase burn severity? Select all that apply.',
    [o('Burns to the face, hands, feet, perineum or major joints', true, 'Function and airway.'), o('Inhalation injury', true, 'Airway threat.'), o('Electrical or chemical mechanism', true, 'Deeper, hidden damage.'), o('Older age or comorbidities', true, 'Less reserve.'), o('A superficial sunburn on the back', false, 'Not counted.')],
    'Severity = depth + TBSA + location + mechanism + patient factors. Not just how the wound looks.', true),
  Q('TBSA', 'Using the adult Rule of Nines, a client with partial-thickness burns to the entire anterior trunk and the entire left arm has a TBSA of:',
    [o('27%', true, 'Anterior trunk 18 + one arm 9.'), o('18%', false, 'Forgot the arm.'), o('36%', false, 'Counted the whole trunk.'), o('45%', false, 'Too high.')],
    'Head 9, each arm 9, anterior trunk 18, posterior trunk 18, each leg 18, perineum 1. Halve a limb value for its front or back only.'),
  Q('TBSA', 'Why is TBSA estimated in the first place, and which depths are included?',
    [o('It drives fluid resuscitation and transfer decisions; partial- and full-thickness burns count, superficial burns do not', true, 'Purpose and rule.'), o('It predicts scarring; all burns count', false, 'Superficial burns are excluded.'), o('It sets the antibiotic dose', false, 'No.'), o('It is only for documentation', false, 'No.')],
    'TBSA × weight × 4 = the Parkland estimate. For small scattered burns, the client\'s palm ≈ 1%.'),
  Q('TBSA', 'The Lund-Browder method is preferred over the Rule of Nines for:',
    [o('Children, because it adjusts for age (a child\'s head is proportionally larger, legs smaller)', true, 'Age-adjusted and more precise.'), o('Adults with electrical burns', false, 'No.'), o('Estimating fluid rate', false, 'It estimates area, not rate.'), o('Superficial burns', false, 'Not counted anyway.')],
    'Rule of Nines is the quick adult estimate; Lund-Browder is precise and age-adjusted.'),
  Q('Initial burn assessment and priorities', 'A client rescued from an enclosed house fire has singed nasal hair, a hoarse voice, and carbonaceous sputum. The priority is:',
    [o('Airway: anticipate rapid swelling and possible early intubation; high-flow humidified oxygen', true, 'Inhalation injury.'), o('Calculate TBSA first', false, 'Airway first.'), o('Apply ice to the burns', false, 'Never ice: hypothermia and deeper injury.'), o('Pain medication first', false, 'Airway.')],
    'Mechanism (enclosed space) + airway findings = inhalation injury. ABCs before the wounds.'),
  Q('Initial burn assessment and priorities', 'Which findings in a burn client require immediate intervention or escalation? Select all that apply.',
    [o('Stridor or increasing hoarseness', true, 'Airway closing.'), o('Urine output 12 mL/hr in a 70 kg adult', true, 'Under-resuscitation.'), o('Circumferential full-thickness burn of a limb with loss of distal pulse', true, 'Escharotomy needed.'), o('New restlessness with falling BP', true, 'Burn shock.'), o('Arm edema with normal urine output and pulses', false, 'Expected.')],
    'Airway, perfusion (whole body and limb), and mental status are the escalation cues.', true),
  Q('Physiological response to major burn', 'Explain why a major-burn client can be visibly swollen yet in hypovolemic shock.',
    [o('Inflammation increases capillary permeability; plasma leaks from the vessels into the interstitial space, so edema rises while circulating volume falls', true, 'Fluid moved to the wrong compartment.'), o('The client received too much IV fluid', false, 'Not the mechanism.'), o('The kidneys retain water', false, 'No.'), o('Swelling means the vessels are full', false, 'The paradox: swollen outside, empty inside.')],
    'Burn → inflammation → capillary leak → interstitial edema + decreased effective circulating volume → decreased perfusion. Predict: HR up, BP and urine down, Hct up (hemoconcentration).'),
  Q('Physiological response to major burn', 'Which lab trends fit the first hours of a major burn? Select all that apply.',
    [o('Hematocrit rising (hemoconcentration)', true, 'Plasma leaves; cells stay.'), o('Potassium rising from cell lysis', true, 'Cardiac risk; monitor rhythm.'), o('Urine output falling', true, 'Renal hypoperfusion.'), o('Hematocrit falling immediately', false, 'Later, with resuscitation and blood loss.'), o('Potassium falling in the first hours', false, 'Falls later, in the diuretic phase.')],
    'Timing matters: early hemoconcentration and hyperkalemia; later, as fluid returns to the vessels, values shift the other way.', true),
  Q('Fluid resuscitation', 'Parkland formula for a 70 kg client with 36% TBSA burned at 1200: total volume and timing?',
    [o('10,080 mL LR in 24 h; half (5,040 mL) by 2000, counted from the TIME OF THE BURN; the rest over the next 16 h', true, '4 × 70 × 36.'), o('10,080 mL; half by 8 hours after admission', false, 'From the burn, not admission.'), o('5,040 mL total in 24 h', false, 'That is the first-half volume.'), o('20,160 mL in 24 h', false, 'Doubled.')],
    'The formula is a starting estimate. Urine output (about 0.5 mL/kg/hr, 30–50 mL/hr) tells you whether it is working.'),
  Q('Fluid resuscitation', 'Why is lactated Ringer\'s preferred over normal saline for burn resuscitation?',
    [o('LR is a balanced crystalloid; large volumes of normal saline deliver a chloride load that can worsen acidosis', true, 'Course note: LR = balanced, NS = high chloride.'), o('LR contains glucose for energy', false, 'No.'), o('NS is hypotonic', false, 'NS is isotonic.'), o('LR contains potassium to replace losses', false, 'Small amount; not the reason.')],
    'Isotonic crystalloid expands the intravascular space; LR does it without the chloride load.'),
  Q('Fluid resuscitation', 'Which findings show burn fluid resuscitation is ADEQUATE? Select all that apply.',
    [o('Urine output about 0.5 mL/kg/hr', true, 'The bedside gold standard.'), o('Heart rate and blood pressure stabilizing', true, 'Perfusion.'), o('Alert and oriented', true, 'Brain perfused.'), o('Hematocrit trending down toward normal', true, 'Plasma restored.'), o('Arm edema visibly less', false, 'Edema persists 24–48 h; not the endpoint.'), o('Pain decreasing', false, 'Not a perfusion marker.')],
    'Evaluate with urine output, hemodynamics, mental status and labs. Both under- and over-resuscitation harm.', true),
  Q('Fluid resuscitation', 'Signs of EXCESSIVE resuscitation include:',
    [o('Crackles, rising oxygen needs, worsening edema in unburned tissue, and compartment pressures rising', true, 'Fluid overload and compartment syndrome.'), o('Urine output 40 mL/hr', false, 'Adequate.'), o('Restlessness with low BP', false, 'Under-resuscitation.'), o('Rising hematocrit', false, 'Under-resuscitation.')],
    'Too much fluid: wet lungs and swelling that compromises limbs and the abdomen. Titrate to urine output, do not run the formula blindly.'),
  Q('Ongoing burn management', 'Which nursing priorities apply to ongoing burn care? Select all that apply.',
    [o('Strict aseptic wound care; the skin barrier is gone', true, 'Infection is the leading late killer.'), o('Pre-medicate before dressing changes; multimodal pain management', true, 'Procedural pain is severe.'), o('High-calorie, high-protein nutrition; hypermetabolism can double energy needs', true, 'Healing.'), o('Keep the client warm; a burned client loses heat rapidly', true, 'Temperature regulation lost.'), o('Apply ice to reduce pain', false, 'Hypothermia and deeper injury.'), o('Restrict protein to protect the kidneys', false, 'Opposite.')],
    'Infection, pain, nutrition, warmth, and constant reassessment for complications.', true),
  /* ---- Fluids & electrolytes ---- */
  Q('Fluid compartments', 'Extracellular fluid (ECF) includes:',
    [o('Intravascular plasma and interstitial fluid', true, 'Outside the cells.'), o('Fluid inside the cells only', false, 'That is ICF.'), o('Only blood', false, 'Also interstitial.'), o('Only lymph', false, 'No.')],
    'ICF = inside cells (the largest compartment). ECF = outside cells: intravascular + interstitial. Key question in burns: where is the water now, and where is it moving?'),
  Q('Fluid movement', 'A hypotonic solution such as 0.45% saline causes water to move:',
    [o('Into the cells (cells swell)', true, 'HYPO → IN → SWELL.'), o('Out of the cells (cells shrink)', false, 'Hypertonic.'), o('Nowhere; no net shift', false, 'Isotonic.'), o('Into the vessels only', false, 'No.')],
    'HYPO → IN → SWELL. HYPER → OUT → SHRINK. ISO → EVEN → SAME. Water moves toward the greater solute concentration.'),
  Q('Fluid movement', 'Which IV solutions are isotonic and expand the intravascular volume? Select all that apply.',
    [o('0.9% sodium chloride (normal saline)', true, 'Isotonic.'), o('Lactated Ringer\'s', true, 'Isotonic, balanced.'), o('0.45% sodium chloride', false, 'Hypotonic.'), o('3% sodium chloride', false, 'Hypertonic: pulls water out of cells; used cautiously for severe hyponatremia or cerebral edema.'), o('D5W once the dextrose is metabolized', false, 'Becomes free water (hypotonic).')],
    'Isotonic for volume. Hypotonic to rehydrate cells. Hypertonic to pull water out of cells, with close monitoring.', true),
  Q('Fluid movement', 'Why are inappropriate water shifts especially dangerous neurologically?',
    [o('Brain cells swell or shrink inside a fixed skull; rapid sodium changes cause confusion, seizures or herniation', true, 'Na = WATER + BRAIN.'), o('The brain has no blood supply', false, 'No.'), o('Water cannot cross into the brain', false, 'It can.'), o('They are not dangerous', false, 'They are.')],
    'Correct sodium slowly; the brain does not tolerate sudden shifts.'),
  Q('Fluid volume alterations', 'Which findings indicate fluid volume DEFICIT? Select all that apply.',
    [o('Tachycardia and orthostatic hypotension', true, 'Compensation for low volume.'), o('Decreased urine output, concentrated urine', true, 'Kidneys conserve.'), o('Weight loss over 24 hours', true, '1 kg ≈ 1 L.'), o('Poor skin turgor, dry mucous membranes', true, 'Classic.'), o('Rising BUN:creatinine ratio', true, 'Pre-renal.'), o('Crackles and JVD', false, 'Excess.')],
    'Deficit = dry and fast. Do not diagnose from one finding; look for the pattern and the trend.', true),
  Q('Fluid volume alterations', 'Which findings indicate fluid volume EXCESS? Select all that apply.',
    [o('Weight gain, edema', true, 'Retention.'), o('Crackles, dyspnea, orthopnea', true, 'Pulmonary congestion.'), o('Jugular venous distension, bounding pulse', true, 'Venous congestion.'), o('Skin tenting', false, 'Deficit.'), o('Orthostatic hypotension', false, 'Deficit.')],
    'Excess = wet and heavy. Daily weight is the best single measure of fluid change.', true),
  Q('Fluid volume alterations', 'A burn client is markedly edematous. What does this tell the nurse about intravascular volume?',
    [o('Nothing reassuring: edema can coexist with intravascular depletion; judge volume by HR, BP, urine output and mentation', true, 'Edema ≠ full vessels.'), o('The vessels are full; slow the fluids', false, 'Dangerous.'), o('The client is over-resuscitated', false, 'Not by edema alone.'), o('Give a diuretic', false, 'Would deepen the deficit.')],
    'Edema does not automatically mean adequate intravascular volume. Use the perfusion scorecard.'),
  Q('Fluid volume alterations', 'Which measurement is most useful for tracking fluid status over time?',
    [o('Daily weight at the same time, same scale, same clothing, with intake and output', true, 'Most reliable trend.'), o('A single blood pressure', false, 'Snapshot.'), o('Skin turgor in an older adult', false, 'Unreliable with aging.'), o('Thirst', false, 'Blunted in older adults.')],
    'Trends beat single values: weight, I&O, urine output, vital signs, labs.'),
  Q('Sodium', 'A client with sodium 148 after two days of poor intake on a diuretic is confused and weak. Nursing priorities?',
    [o('Replace water carefully (oral or hypotonic/isotonic fluids as ordered), hold the diuretic and clarify, safety precautions, monitor sodium and neuro status', true, 'Hypernatremia from water loss.'), o('Restrict fluids', false, 'Backwards.'), o('Give 3% saline', false, 'Would worsen it.'), o('Encourage salty foods', false, 'No.')],
    'Hypernatremia = water deficit relative to sodium: thirst (if intact), restlessness, confusion, weakness. Na = WATER + BRAIN; correct gradually.'),
  Q('Sodium', 'Which manifestations fit hyponatremia? Select all that apply.',
    [o('Confusion, lethargy, headache', true, 'Cerebral edema.'), o('Nausea, muscle cramps', true, 'Common.'), o('Seizures at very low levels', true, 'Emergency.'), o('Peaked T waves', false, 'Hyperkalemia.'), o('Chvostek sign', false, 'Hypocalcemia.')],
    'Low sodium lets water into brain cells. Causes: excess water (SIADH, excess hypotonic fluid), losses (vomiting, diuretics). Correct slowly.', true),
  Q('Potassium', 'A burn client\'s potassium rises to 6.4 with peaked T waves. Which actions are correct? Select all that apply.',
    [o('Continuous cardiac monitoring; notify the provider immediately', true, 'Lethal dysrhythmia risk.'), o('IV calcium gluconate first to protect the heart', true, 'Stabilizes the membrane.'), o('IV regular insulin with dextrose to shift potassium into cells', true, 'Temporary shift.'), o('Hold potassium-containing fluids and supplements', true, 'Stop the source.'), o('Give potassium chloride IV push', false, 'Never; and never in hyperkalemia.'), o('Encourage bananas and orange juice', false, 'High in potassium.')],
    '"Calcium to protect, insulin + dextrose to shift, then remove (diuretics, binders, dialysis)." K = HEART.', true),
  Q('Potassium', 'A client on furosemide has potassium 3.0, muscle weakness and a flattened T wave with a U wave. The nurse anticipates:',
    [o('Oral or IV potassium replacement (IV always diluted and by pump, never push), cardiac monitoring, and checking magnesium', true, 'Hypokalemia; Mg must be normal for K to correct.'), o('Calcium gluconate', false, 'That is for hyperkalemia with ECG changes.'), o('Insulin and dextrose', false, 'Would lower potassium further.'), o('Fluid restriction', false, 'No.')],
    'Loop diuretics waste potassium. Hypokalemia: weakness, cramps, dysrhythmias, flat T, U waves; dangerous with digoxin.'),
  Q('Potassium', 'On an insulin drip for DKA, potassium falls from 5.5 to 2.9 in three hours. What happened, and what is the priority?',
    [o('Insulin drove potassium into the cells; replace potassium per protocol once urine output is confirmed and slow the drip if ordered', true, 'The potassium trap.'), o('The lab is wrong', false, 'Expected physiology.'), o('Give more insulin to lower the glucose faster', false, 'Would drop potassium further.'), o('Nothing; potassium will rebound', false, 'It will not.')],
    'DKA: fluids first, insulin second, watch the potassium plummet. Always confirm urine output before adding potassium.'),
  Q('Calcium', 'Which findings indicate hypocalcemia? Select all that apply.',
    [o('Positive Chvostek sign (facial twitch) and Trousseau sign (carpal spasm with BP cuff)', true, 'Neuromuscular irritability.'), o('Tingling around the mouth and in the fingers', true, 'Paresthesias.'), o('Muscle cramps, tetany, laryngospasm at severe levels', true, 'Airway risk.'), o('Kidney stones and constipation', false, 'Hypercalcemia.'), o('Bone pain and lethargy', false, 'Hypercalcemia.')],
    'Ca = NERVES + MUSCLES. Low calcium = twitchy; high calcium = sluggish (weakness, constipation, stones, confusion). Check albumin and magnesium.', true),
  Q('Magnesium', 'A client with alcohol use disorder has magnesium 1.1, hyperactive reflexes and a prolonged QT. Nursing priorities?',
    [o('Cardiac monitoring (torsades risk), IV magnesium as ordered, seizure precautions, and check potassium and calcium', true, 'Mg = RHYTHM + REFLEXES.'), o('Restrict fluids', false, 'No.'), o('Give calcium gluconate', false, 'That is the antidote for magnesium EXCESS.'), o('No action; mildly low', false, 'Dangerous.')],
    'Hypomagnesemia: hyperreflexia, tremors, dysrhythmias (torsades). Hypermagnesemia: loss of reflexes, respiratory depression, hypotension; antidote calcium gluconate.'),
  Q('Magnesium', 'A client receiving IV magnesium has absent deep tendon reflexes and RR 10. The nurse should:',
    [o('Stop the infusion, notify the provider, and prepare calcium gluconate', true, 'Magnesium toxicity.'), o('Increase the rate', false, 'No.'), o('Give more magnesium', false, 'No.'), o('Document as expected', false, 'Emergency.')],
    'Loss of reflexes is the first sign of magnesium excess; respiratory depression follows. Reflexes are checked before every dose.'),
  Q('Phosphate', 'Which statements about phosphate are correct? Select all that apply.',
    [o('Phosphate and calcium move in opposite directions', true, 'Inverse relationship.'), o('Low phosphate causes weakness, poor cellular energy (ATP) and respiratory muscle weakness', true, 'Phosphate = ATP + STRENGTH.'), o('Refeeding after starvation can drop phosphate sharply', true, 'Refeeding syndrome.'), o('High phosphate is common with kidney failure', true, 'Kidneys excrete it.'), o('Phosphate has no cardiac or neurologic effects', false, 'It does, through calcium and ATP.')],
    'For every electrolyte: cause, symptoms, kidney function, medications, acid-base context, trend.', true),
  Q('Burns and electrolyte balance', 'A burn client\'s potassium is 5.6 at hour 4 and 3.4 on day 3. The nurse interprets:',
    [o('Early rise from cell lysis and poor renal perfusion; later fall as fluid shifts back, diuresis begins and potassium moves into cells: phase and trend matter more than one value', true, 'Course emphasis: timing and trends.'), o('A lab error', false, 'Expected pattern.'), o('Burns always cause hypokalemia', false, 'Do not memorize one fixed pattern.'), o('Give potassium at hour 4', false, 'It is high then.')],
    'Tissue injury, fluid shifts, renal perfusion, acid-base changes and treatment all move electrolytes. Interpret in context, in sequence.'),
  Q('Clinical judgment', 'A simulated chart at 1400 → 1600: HR 104 → 126, BP 112/72 → 88/54, RR 22 → 28, SpO₂ 96 → 92%, urine 45 → 18 mL/hr, K⁺ 4.2 → 5.6, Hct 43 → 50%, alert → restless. Which cues belong together as worsening perfusion?',
    [o('HR up, BP down, urine output down, restlessness', true, 'One story: hypovolemia.'), o('SpO₂ and RR only', false, 'Respiratory trend, needs its own reassessment.'), o('Potassium alone', false, 'Cardiac implication, separate concern.'), o('None; each value is within a tolerable range', false, 'Trends, not thresholds.')],
    'What changed? Which cues belong together? What is the priority? What should happen next? What will you reassess?')
);

/* ---- Study-guide cards ---- */
[
  ['Exam 1 facts', 'Exam 1 format', 'Friday September 25 · 75 questions · includes 2 NGN respiratory case studies (six steps each).', 'Cases completed in class are the model for the NGN items.'],
  ['Exam 1 facts', 'The five questions the exam expects you to ask', 'What do I notice? · What does it mean? · What is the priority? · What should I do? · Did it work?', 'Recognize → Analyze → Prioritize → Act → Evaluate.'],
  ['Trauma / shock', 'Hypovolemic shock picture', '"Fast, cold, pale, dry, dizzy." HR up, BP down, cool pale skin, urine down, confusion. Warm skin = a different shock.', 'Femur fracture can hide a liter.'],
  ['Trauma / shock', 'Comorbidity twist', 'Hypertension + lisinopril: her "normal" BP is low for her and the ACE inhibitor blunts compensation. Diabetes + metformin: stress hyperglycemia, hold metformin around surgery/contrast, healing and infection risk.', ''],
  ['Case Study 2 meds', 'Seven meds, one line each', 'Aspirin = antiplatelet after ischemic stroke · Metoprolol = beta-blocker, hold HR < 60 · KCl = replace 3.2, liquid via tube, never crush ER, never IV push · Pantoprazole = acid protection, DR suspension only · Glargine = basal, never mixed · Lispro = rapid correction · Acetaminophen = watch the daily total.', ''],
  ['Neuro', 'Order of ICP signs', 'LOC change (earliest) → pupil change → Cushing\'s triad (late: pressure HIGH, pulse LOW, breathing WEIRD).', 'Escalate on the LOC change; do not wait for the triad.'],
  ['Neuro', 'GCS rule of thumb', 'A drop of 2 or more points = escalate now. 8 or less = airway.', 'Chart the trend, not the score.'],
  ['Neuro', 'Focal vs global', 'Focal = one side, one function (face, arm, speech) → stroke pathway. Global = LOC, pupils, vomiting, breathing → pressure pathway.', ''],
  ['Neuro', 'Stroke clock', 'Last known well starts the clock. Sugar, scan, plan. BP < 185/110 for alteplase. No aspirin until the CT says no bleed.', ''],
  ['Neuro', 'Decline during alteplase', 'STOP the drip · ESCALATE · STABILIZE airway/breathing/circulation · CONFIRM with CT. Bleed until proven otherwise.', ''],
  ['Neuro', 'Seizure timeline', 'Protect + time it. 5 minutes = status epilepticus → benzodiazepine → then watch the BREATHING. Post-ictal sleepy-but-arousable is expected; RR 8 is not.', ''],
  ['Neuro', 'Spinal vs neurogenic shock', 'Spinal = NERVES flat (flaccid, areflexic; resolves when reflexes return). Neurogenic = PRESSURE flat (low BP, low HR, warm dry skin; T6+; needs pressors/atropine).', 'Both can happen at once.'],
  ['Neuro', 'Autonomic dysreflexia', 'Trigger below (bladder > bowel > skin) → BP skyrockets, pounding headache, flushed above / pale below. SIT, LOOSEN, DRAIN, RECHECK. Never lie flat.', ''],
  ['Respiratory', 'ABG in 3 steps', '1) pH: acid (< 7.35) or base (> 7.45)? 2) Which matches: CO₂ (respiratory, opposite direction) or HCO₃⁻ (metabolic, same direction)? 3) Compensation: other value moving = partial; pH normal = full.', 'pH 7.35–7.45 · CO₂ 35–45 · HCO₃ 22–26 · PaO₂ 80–100'],
  ['Respiratory', 'Respiratory conditions in one breath', 'Pneumonia = fever, purulent sputum, crackles, WBC up → cultures, antibiotics, O₂, fluids, TCDB. ARDS = refractory hypoxemia → vent, prone. PE = sudden pleuritic pain + hypoxemia + DVT → O₂, heparin, CTPA. TB = RIPE, airborne, DOT. Asthma = SABA + steroid, silent chest is danger. COPD = 88–92%, pursed lip, no cough suppressant.', ''],
  ['Respiratory', 'Drugs to question in asthma', 'Non-selective beta-blockers, NSAIDs, aspirin.', '"Labetalol and ibuprofen make the airway tighten."'],
  ['Burns', 'Depth in one line each', 'Superficial: red, dry, painful, NOT counted. Partial: blisters, moist, painful. Full: dry, leathery, less sensate.', 'Pain never grades severity.'],
  ['Burns', 'Rule of Nines', '9 head · 9 each arm · 18 front · 18 back · 18 each leg · 1 perineum. Halve a limb for front/back only. Palm ≈ 1%. Lund-Browder = kids (age-adjusted).', ''],
  ['Burns', 'Parkland', '4 mL × kg × %TBSA of LR over 24 h. Half in the first 8 h FROM THE TIME OF THE BURN. Goal urine 0.5 mL/kg/hr (30–50 mL/hr). LR because NS = chloride load.', 'The formula starts; urine output steers.'],
  ['Burns', 'Inhalation injury cues', 'Enclosed space · singed nasal hair · hoarse voice · carbonaceous sputum · facial burns · stridor. Airway swells fast: early intubation.', ''],
  ['Burns', 'The burn paradox', 'Capillary leak → swollen OUTSIDE, empty INSIDE. Hct rises, K⁺ rises early, urine falls. Edema never means the vessels are full.', ''],
  ['Fluids', 'Compartments', 'ICF inside cells (largest). ECF outside: intravascular + interstitial. Ask: where is the water now, and where is it moving?', ''],
  ['Fluids', 'Tonicity', 'HYPO → IN → SWELL (0.45% NS). HYPER → OUT → SHRINK (3% NS). ISO → EVEN → SAME (0.9% NS, LR). D5W becomes free water.', ''],
  ['Fluids', 'Deficit vs excess', 'Deficit = dry and fast (tachycardia, orthostasis, low urine, weight down, BUN:Cr up). Excess = wet and heavy (crackles, edema, JVD, weight up, orthopnea). Daily weight: 1 kg = 1 L.', ''],
  ['Electrolytes', 'Electrolyte jobs', 'Na = WATER + BRAIN · K = HEART + MUSCLE · Ca = NERVES + MUSCLES · Mg = RHYTHM + REFLEXES · PO₄ = ATP + STRENGTH', 'Forget the list? Start with the job.'],
  ['Electrolytes', 'Potassium emergencies', 'HIGH: peaked T → calcium gluconate, insulin + dextrose, then remove. LOW: flat T, U wave, weakness → replace (never IV push), check Mg.', 'Never IV push potassium. Ever.'],
  ['Electrolytes', 'Calcium and magnesium signs', 'Low Ca: Chvostek, Trousseau, tingling, tetany. High Ca: weak, constipated, stones, confused. Low Mg: hyperreflexia, torsades. High Mg: no reflexes, slow breathing → calcium gluconate.', ''],
  ['Electrolytes', 'Burns and electrolytes', 'Early: K⁺ up (cell lysis), Hct up. Later: K⁺ and Na⁺ fall with diuresis and shifts. Phase + kidney function + treatment + trend, never one value alone.', '']
].forEach(([cat, front, back, tip]) => window.RHYMES.push({ cat, front, back, tip, source: SG }));
})();
